thirdweb-dev/js

.changeset/tame-adults-breathe.md, packages/sdk/src/constants/addresses.ts, packages/sdk/src/constants/currency.ts
Biconomy forwarder addresses source: https://docs.biconomy.io/misc/contract-addresses#eip-2771-contracts-trusted-forwarder
Not available for Arbitrum-Goerli and Optimism-Goerli.
=> [SDK] Update addresses

.changeset/modern-monkeys-turn.md, packages/sdk/src/evm/common/nft.ts, packages/sdk/src/evm/core/classes/erc-1155.ts, packages/sdk/src/evm/core/classes/erc-721.ts
For contracts that don't have sequential tokenIds or start at a given index, avoid failing the entire getAll() call. Instead return a "failure" metadata when trying to get non-existent token ids. Like this one https://thirdweb.com/ethereum/0xeb4e856f69158052ac0aaf7dc26f63dcb1ee067f
Put it in the single get() to make it consistent between getAll() and get(). But open to changing it.
=> [SDK] return fallback metadata when tokenId is not found on nft contract

.changeset/dry-pandas-clap.md, packages/react/src/evm/contexts/thirdweb-config.tsx, packages/react/src/evm/contexts/thirdweb-wallet.tsx, packages/react/src/evm/providers/full.tsx, packages/sdk/src/evm/constants/urls.ts
The problem was that we were *always* passing a readonly url to UserWallet, but this readonly url relies on passing a rpcURLMap from ThirdwebProvider which seems wrong. 
When using ThirdwebSDKProvider we don't let you pass that rpcUrl map at all.
What would happen is that `const rpcUrl = rpcUrlMap[chainId];` would resolve in "mumbai" and would try to override the provider within the signer with a readonly provider, only to fail and throw since `ethers.getProvider("mumbai")` throws. That would manifest in no signer being available when doing things like SIWE. See thread in https://discord.com/channels/834227967404146718/1019059287030505562/1030917794939813988
=> [React] Fix passing wrong RPC url to UserWallet when using an external signer

.changeset/khaki-panthers-grin.md, packages/sdk/src/evm/core/classes/erc-1155-signature-mintable.ts, packages/sdk/test/evm/publisher.test.ts
This is a patch for the ERC1155 Signature Mint function in the SDK.
The current function uses the domain `TokenERC1155` which should actually match the domain in the smart contract, which is [`SignatureMintERC1155`](https://github.com/thirdweb-dev/contracts/blob/main/contracts/extension/SignatureMintERC1155.sol#L18). Because the domains do not match, the signer recovered after processing the request will always be different. This means all transactions will fail as the signer recovered is not expected.
This change was also communicated and discussed with @adam-maj on Discord after a week of debugging.
Changes were tested according to contributing guidelines!
=> [SDK] Update signTypedData domain to match contract

.changeset/rich-pigs-cry.md, packages/react/src/evm/hooks/async/drop.ts, packages/react/src/evm/utils/cache-keys.ts
`useClaimedNFTs` was fetching all nfts from the contract by calling `useNFTs`. This makes it so we call getAllClaimed from the contract
Tested:
- Locally imported the package and made sure only claimed NFTs were returned
=> [ReactSDK] Changes useClaimedNFTs to only fetch claimed NFTs

.changeset/good-seahorses-applaud.md, packages/auth/README.md, packages/auth/package.json
Made this change because if you install `@thirdweb-dev/auth` with `npm` instead of `yarn`, it throws error on peer dependencies not matching:
- Switched  `next` peer dependency to `^12 || ^13` to allow both next 12 and 13 setups.
- Switched `ethers`, `express`, and `next-auth` to just specify major version
- Removed `@thirdweb-dev/sdk` as peer dependency from auth since it's no longer used
=> [Auth] Update peerDependencies

.changeset/beige-lizards-hug.md, packages/sdk/src/evm/common/error.ts, packages/sdk/src/evm/core/classes/contract-deployer.ts, packages/sdk/src/evm/core/classes/contract-wrapper.ts, packages/sdk/test/evm/errors.test.ts
When the user has no funds, we want to throw a more informative error that lets users know this. However, we also need to preserve the UX of a transaction popping for users with wallets like MetaMask where they will see on UI that they have insufficient funds for the transaction, so we can't throw before `sendTransaction`.
The solution is to let `estimateGas` fail, but then if the error is due to insufficient funds, `callStatic` will succeed and we can let it pass through to `sendTransaction`. Then, when we catch `sendTransaction`, we can check if user balance is insufficient and throw an informative error.
**Update:** Additionally, if we manually set `gasLimit`, `sendTransaction` will always go through. However, `sendTransaction` can succeed, and then we can error on `tx.wait()` - in …
=> [SDK] Add proper error catching for when user has no funds

packages/react-core/src/evm/providers/thirdweb-sdk-provider.tsx
Passing the default key in the top most provider so that it propagates correctly to the rest of the providers (ThirdwebConnectedWalletProvider was not getting the key since it was not being set in the Context)
=> [ReactCoreSDK] pass default key to the sdkprovider

.changeset/stupid-moles-boil.md, packages/react-core/src/evm/providers/thirdweb-sdk-provider.tsx
=> Fix Wrong Currency symbol in non-default chains

.changeset/witty-lizards-doubt.md, packages/react-core/src/evm/hooks/async/drop.ts
Hooks `useUnclaimedNFTs()`, `useClaimedNFTs()`, `useUnclaimedNFTSupply()`, and `useClaimedNFTSupply()` don't work with edition drop contracts, however, the comments on these hooks specified they could.
=> [React] Fix accepted types for some hooks

packages/react-core/src/core/providers/thirdweb-provider.tsx, packages/react-core/src/core/providers/thirdweb-wallet-provider.tsx, packages/react-core/src/core/utils.ts, packages/react-core/src/index.ts, packages/react-native/src/evm/wallets/connectors/coinbase-wallet/index.ts, packages/react/package.json, packages/react/src/components/Popover.tsx, packages/react/src/components/Spinner.tsx, packages/react/src/design-system/index.ts, packages/react/src/evm/components/Web3Button/index.tsx, packages/react/src/wallet/ConnectWallet/Connect.tsx, packages/react/src/wallet/ConnectWallet/Details.tsx, packages/react/src/wallet/ConnectWallet/NetworkSelector.tsx, packages/react/src/wallet/ConnectWallet/screens/Coinbase/CoinbaseScan.tsx, packages/react/src/wallet/ConnectWallet/screens/ConnectingScreen.tsx, packages/react/src/wallet/ConnectWallet/screens/DeviceWallet/DeviceWalletSetup.tsx, packages/react/src/wallet/ConnectWallet/screens/Metamask/MetamaskScan.tsx, packages/react/src/wallet/ConnectWallet/screens/ScanScreen.tsx, packages/react/src/wallet/hooks/useCanSwitchNetwork.ts, packages/wallets/src/evm/connectors/coinbase-wallet/index.ts, packages/wallets/src/evm/connectors/injected/index.ts, packages/wallets/src/evm/connectors/wallet-connect-v1/index.ts, packages/wallets/src/evm/wallets/base.ts, packages/wallets/src/evm/wallets/metamask.ts, packages/wallets/src/lib/wagmi-connectors/Connector.ts, scripts/hotlink/changes.mjs, yarn.lock
- Stop forcing network switch when connecting wallet
- add autoSwitch option to force network switch in ThirdwebProvider
- remove deprecated and unused `chainRpc` prop from `ThirdwebProvider` 
- remove unused and confusing state 'activeChain' in wallet-provider
- Re export types from /sdk in /react-core
- Fix wrong RPC urls and explorer URLs in wallets package
- make switchChain public in wallet connect v1 and remove walletName check
- Add "Confirm in Wallet" UI in Web3Button, Network Switcher
- Fix hotlink DX
=> Connect wallet v2 various improvements

packages/react-core/src/core/providers/thirdweb-wallet-provider.tsx, packages/react-core/src/core/types/wallet.ts, packages/react-core/src/evm/index.ts, packages/wallets/src/evm/wallets/device-wallet.ts
* Device wallet's connect method requires connectParams - it can not be optional
* the `connect` function returned from `useConnect` should reflect the same
* if the wallet's connect method does require connectParams, `connect` should be able to accept only one arg - the wallet class
```js
const connect = useConnect();
connect(MetamaskWallet, {}) // must provide second arg
```
```js
const connect = useConnect();
connect(MetamaskWallet) // ok
connect(DeviceWallet) // type error - connectParams are required
connect(DeviceWallet, { password: '123xyz' }) // ok
```
=> Fix useConnect() type

packages/wallets/package.json, yarn.lock
Need to lock to a minor version for @walletconnect/ethereum-provider (~2.4.6) because 2.5.1 is not working for us
we can figure out how to make it work with the newer version later
=> fix wallet connect v2 error 

.changeset/curly-rice-wash.md, packages/sdk/src/evm/common/feature-detection.ts, packages/sdk/src/evm/core/classes/contract-publisher.ts
Removing abischema.parse from `extractFunctionsAbi` for perf improvements. It improved loading times by 26x since we call extractFunctionsFromAbi ~2k times the first time we load an ABI. This should be save to remove since we do set a default value in the schema, it's just that zod treats `.default` as an optional when it comes to the types.
Follow ups:
- Investigate how to improve extractFunctionsAbi, maybe look into parsing the ABI only once and store the parsed value during the creation of the contract?
=> [SDK] Dont parse abis on detect features

.changeset/cool-spies-melt.md, packages/sdk/src/evm/schema/contracts/common/signature.ts
For compatibility reasons with other SDKs and performance (you don't need the metadata in this call, so don't force people to fetch it down just to pass it here)
=> [SDK] Make metadata signature 721 output optional

.changeset/real-poets-swim.md, packages/cli/src/create/helpers/create-app.ts
Only checks ruby version and attempts to run pod install if the platform is macOS.
Uses `process.platform` to identify OS: https://nodejs.org/api/process.html#processplatform
=> [CLI] Only run react-native ios specific tasks on macOS envs

.changeset/spicy-carrots-grin.md, packages/react/src/wallet/ConnectWallet/ConnectWallet.tsx
Added an onLogin callback to the authOptions props of the ConnectWallet.tsx component to be able to use the JWT
=> [REACT] Add onLogin callback to ConnectWallet authOptions props

.changeset/rotten-badgers-build.md, packages/react-native/src/evm/components/Web3Button.tsx
The Web3Button action prop didn't return a promise, meaning devs can do:
```
<Web3Button action={() => {contract.call()}} ...
```
This will return `void` which breaks the `onError` and `onSuccess` props.
Forcing the `action` prop to return a Promise will raise an error in the example above and make the user return a promise, like so:
```
<Web3Button action={() => {return contract.call()}} ...
```
which will make the other props work as expected
=> [ReactNative] Make web3button action return a promise

packages/sdk/src/evm/constants/currency.ts
an update from https://github.com/thirdweb-dev/js/pull/987
as brought to my attention by [this twitter thread](https://twitter.com/kassandraeth/status/1659586527498780676?s=12&t=FJ9Ia-2v_9ftxl0My0axTg), the Aave WETH contract has a mint function in it. WETH should not have a mint function that can be called by the contract owner. Until a defacto standard emerges, we should move to a WETH contract that mirrors mainnet and has a lot of usage. 
@joaquim-verges [was right](https://github.com/thirdweb-dev/js/pull/987#pullrequestreview-1425799427), this contract is the better one.
=> update sepolia weth to an address that does not have a mint function

.changeset/five-frogs-learn.md, packages/sdk/src/evm/core/classes/contract-wrapper.ts
Read calls to view/pure functions can have `from` and `blockTag` as call overrides.
=> [SDK] Allow overrides for read actions

.changeset/modern-plants-design.md, packages/react/src/wallet/wallets/safe/SelectAccount.tsx, packages/react/src/wallet/wallets/smartWallet/SmartWalletConnecting.tsx
Fixes the issue of Magic Link's "Switch Network" not working with Smart Wallet and Safe
=> useSwitchChain instead of wallet.switchChain

packages/wallets/src/evm/connectors/smart-wallet/index.ts
The try/catch was not catching the error because `factory.call` returns a Promise. Promises are "eager", meaning that they start executing as soon as they are created, and any errors they throw won't be caught by a try/catch block because those errors happen asynchronously, outside the try/catch block's synchronous control flow.
Added here: https://github.com/thirdweb-dev/js/pull/1073
=> [Wallets] Fix bug getting account address

.changeset/nine-pumpkins-shop.md, packages/wallets/src/evm/connectors/injected/index.ts, packages/wallets/src/evm/connectors/metamask/index.ts
Solution take from Wagmi MetaMask connector : 
https://github.com/wagmi-dev/references/commit/85330c1ceeb4e0e69b974cb9c87f6146015e3d9f
`shimChainChangedDisconnect` and `#switchingChains` removed as it's no longer relevant
=> [wallets] Fix disconnect on switchChain in MetaMask

packages/react-native/package.json, packages/react-native/src/evm/providers/thirdweb-provider.tsx, pnpm-lock.yaml
Makes:
Needed by Connect an App feature
- react-native-camera  
On Android, users need to add `missingDimensionStrategy 'react-native-camera', 'general'` in `android/app/build.gradle`
```javascript
defaultConfig {
applicationId "com.test15"
minSdkVersion rootProject.ext.minSdkVersion
targetSdkVersion rootProject.ext.targetSdkVersion
missingDimensionStrategy 'react-native-camera', 'general'
versionCode 1
versionName "1.0"
}
```
Needed by Magic implementation
- react-native-safe-area-context
- react-native-webview
- react-native-device-info
=> [ReactNative] Make magic deps and camera deps optional

.changeset/khaki-apricots-flow.md, packages/sdk/src/evm/common/feature-detection/fetchPreDeployMetadata.ts, packages/sdk/src/evm/common/fetchContractMetadata.ts, packages/sdk/src/evm/common/fetchSourceFilesFromMetadata.ts, packages/sdk/src/evm/common/metadata-resolver.ts, packages/sdk/src/evm/common/verification.ts, packages/sdk/src/evm/core/classes/contract-publisher.ts, packages/sdk/src/evm/core/classes/contract-wrapper.ts, packages/sdk/src/evm/core/classes/transactions.ts
Move `fetchContractMetadata` and `fetchSourceFilesFromMetadata` to their own files
=> [sdk] Reduce circular dependencies

.changeset/swift-donkeys-help.md, packages/react/src/wallet/ConnectWallet/NetworkSelector.tsx
If the `supportedChains` are very long - opening the network switcher takes a long time - it feels unresponsive. ( Happens in Dashboard )
So, instead of rendering that upfront - defer rendering it and show a "loading" text while that's being done. Do this only when `supportedChains.length > 100`
We can not show a spinner - because rendering the list blocks the paint (animations)
=> [react] Improve rendering of long Network List in ConnectWallet Modal

.changeset/cyan-chefs-compete.md, packages/wallets/src/evm/connectors/smart-wallet/lib/base-api.ts
Celo and its testnets do not support the BASEFEE opcode, which is called by the ERC-4337 EntryPoint when doing on-chain gas price checks. This can be avoided however by setting the maxPriorityFeePerGas to be the same as the maxFeePerGas
=> [Smart Wallet] Fix Celo support

.changeset/brown-points-sin.md, packages/cli/src/generate/command.ts
Sometimes in builds it would use the old version and the build fails. 
`command not found 'generate'`
This should prevent that happening by fetching latest versions always
=> fix: always use latest CLI version to prevent build failures in CI

.changeset/twelve-moons-do.md, packages/storage/src/common/urls.ts
This removes a gateway destination that does not seem to work with many ISPs.
=> Remove ipfs-2 gateway

.changeset/twenty-dryers-whisper.md, packages/react-core/src/core/hooks/useNetwork.ts
Remove useActiveChain, update to useChain
=> [React] Stop using useActiveChain deprecated hook

.changeset/cool-actors-tease.md, packages/sdk/src/evm/constants/royaltyEngine.ts
Removing incorrect addresses for these testnets: Avalanche-fuji, Arbitrum-goerli, Optimism-goerli, Binance-testnet.
These chains seem unsupported (or don't support correct version of RoyaltyEngineV1 interface). Hence defaulting to zero address on these testnets.
=> Remove incorrect Royalty Engine addresses

.changeset/happy-poets-hang.md, packages/cli/src/generate/command.ts
Post install now adds `thirdweb@latest generate`, but checks for `thirdweb generate`, so every time you run it it adds to itself
=> fix: postinstall check keeps adding to itself

.changeset/olive-crabs-compete.md, packages/react-core/src/evm/providers/thirdweb-sdk-provider.tsx, packages/sdk/src/evm/core/sdk.ts, packages/service-utils/src/core/authorize/client.test.ts, packages/service-utils/src/core/authorize/client.ts, packages/service-utils/src/core/authorize/service.test.ts, packages/service-utils/src/core/authorize/service.ts
This [Error Doc](https://docs.google.com/spreadsheets/d/11pdtjsZAPThBtuP8oez0Uzt5eFg5Rc7_kpXfxJybxoQ/edit#gid=0) has the details on the Error messages that needs to be sent.
on SDK : 
we detect if its backend & `clientId` is provided, we show warning/error message, `Please provide a secret key instead of the clientId. Create a new API Key at https://thirdweb.com/create-api-key`
=> updated error messages for API Keys

.changeset/smart-cheetahs-doubt.md, packages/service-utils/src/cf-worker/usage.ts
The response body did not match Amazon's custom content-type header and logs a warning to console:
```
Called .text() on an HTTP body which does not appear to be text. The body's Content-Type is "application/x-amz-json-1.0". The result will probably be corrupted. Consider checking the Content-Type header before interpreting entities as text.
```
=> [service-utils] Silence publishUsageEvents() output

.changeset/empty-swans-guess.md, .changeset/purple-brooms-hope.md, packages/chains/chains/813.ts, packages/chains/chains/8131.ts, packages/chains/chains/9818.ts, packages/chains/chains/9819.ts, packages/sdk/src/evm/constants/urls.ts, pnpm-lock.yaml, test/e2e/cra-5/package.json, turbo.json
- RPC secret key was not being passed if clientId even existed on options
- clientID was not being computed when secret key was passed
- clientID was not being passed as /path
=> refactor(urls): Simplify authentication strategy handling

.changeset/curly-mirrors-hunt.md, package.json, packages/storage/src/common/urls.ts, packages/storage/src/common/utils.ts, packages/storage/src/core/downloaders/storage-downloader.ts, packages/storage/src/core/storage.ts
`resolveScheme` did not consider `clientId` at all
=> feat(urls): add clientId parameter to getGatewayUrlForCid

.changeset/chilled-planets-search.md, .changeset/loud-stingrays-hide.md, packages/sdk/src/evm/constants/urls.ts, packages/service-utils/src/cf-worker/index.ts, packages/service-utils/src/core/authorize/index.ts, packages/service-utils/src/node/index.ts, packages/storage/src/core/downloaders/storage-downloader.ts, packages/storage/src/core/uploaders/ipfs-uploader.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/http-rpc-client.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/paymaster.ts
previously client libs were possibly sending empty auth tokens, and service utils was treating them as valid
=> [multi] only evaluate auth token if it is a valid string

.changeset/proud-kings-beam.md, packages/sdk/src/evm/core/classes/drop-claim-conditions.ts, packages/sdk/src/evm/core/classes/drop-erc1155-claim-conditions.ts, packages/sdk/src/evm/enums/ClaimEligibility.ts, packages/sdk/test/evm/edition-drop-v4.test.ts, packages/sdk/test/evm/nft-drop-v4.test.ts
- We weren't exposing an easy way to check how many tokens have been claimed by a wallet
- We weren't returning a proper ineligibility reason when trying to claim more than maxClaimablePerWallet
=> [SDK] Expose erc721.claimConditions.getSupplyClaimedByWallet()

.changeset/funny-waves-nail.md, packages/react-native/src/evm/utils/uri.ts, packages/react-native/src/evm/wallets/connectors/coinbase-wallet/index.ts, packages/wallets/src/evm/connectors/blocto/index.ts, packages/wallets/src/evm/connectors/coinbase-wallet/index.ts, packages/wallets/src/evm/connectors/frame/index.ts, packages/wallets/src/evm/connectors/injected/index.ts, packages/wallets/src/evm/connectors/wallet-connect/index.ts, packages/wallets/src/evm/utils/url.ts
We were passing RPC urls with client id restrictions to external wallets
=> [Wallets] use RPCs with no client id when adding to external wallets

.changeset/silent-kiwis-rescue.md, packages/sdk/src/evm/constants/contract-features.ts, packages/sdk/src/evm/constants/thirdweb-features.ts, packages/sdk/src/evm/core/classes/account-permissions.ts, packages/sdk/src/evm/core/classes/account.ts
We could not detect simple ERC4337 accounts if they didnt implement our permissions layer
`FEATURE_ACCOUNT` - any erc4337 account
`FEATURE_ACCOUNT_PERMISSION` - permission layer
separated the account-permission.ts class with its own contract detection nested within account.ts
=> [SDK] Separate Account and AccountPermissions extensions

.changeset/nice-lions-move.md, packages/sdk/src/evm/core/sdk.ts
internal SDK instances were created with default storage instead of passed in custom storage
=> [SDK] Pass custom storage to internal SDK instances

.changeset/sixty-garlics-dance.md, packages/sdk/src/evm/core/classes/transactions.ts
expose a way to get the fully populated tx for signing somewhere else
=> [SDK] Expose Transaction.populateTransaction()

.changeset/ninety-camels-share.md, packages/sdk/src/evm/core/classes/drop-claim-conditions.ts, packages/sdk/src/evm/core/classes/drop-erc1155-claim-conditions.ts
speed up getClaimIneligibility checks when a ineligibility condition is hit
=> [SDK] Return early for claim checks when possible

.changeset/sweet-apricots-guess.md, packages/chains/chains/165.ts, packages/chains/chains/1663.ts, packages/chains/src/index.ts, packages/sdk/src/evm/common/currency/approveErc20Allowance.ts, packages/sdk/src/evm/common/currency/hasERC20Allowance.ts, packages/sdk/src/evm/common/currency/normalizeAmount.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/edition-drop.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/edition.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/nft-collection.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/nft-drop.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/signature-drop.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/split.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/token-drop.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/token.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/vote.ts, packages/sdk/src/evm/contracts/smart-contract.ts, packages/sdk/src/evm/core/classes/account-permissions.ts, packages/sdk/src/evm/core/classes/contract-owner.ts, packages/sdk/src/evm/core/classes/contract-sales.ts, packages/sdk/src/evm/core/classes/contract-wrapper.ts, packages/sdk/src/evm/integrations/thirdweb-checkout.ts
This PR introduces a basic pattern for centralizing contract reads within the SDK itself.
- Have a `call` function that already exists today. Is this something that we want to use?  (not typesafe auto completion though 😢 )
- Not used anywhere. Seems to be exposed as an external API through the pre-built contracts.
- We don't need things to be too clean. will be swapped out with viem items in a bit
- Typescript limitation means we have something like [contract-sales.ts](https://github.com/thirdweb-dev/js/pull/1520/files#diff-e9e0cc9e7ffcc3798766eeba7b78fa939dd0c53692ca0bcfd655d4dc043b318eR41) for generic `ContracttWrapper` (we cannot have partial inferred optional types. I might update the types as I centralize more of the reads, but I think this should tide us over for now till Viem in …
=> feat(sdk): centralize contract reads

.changeset/fifty-radios-grin.md, packages/react-native/src/evm/wallets/wallets/coinbase-wallet.ts
Some users where facing issues with their metro configurations and how we dynamically imported the coinbase connector. Since this didn't have any real utility for us since we already statically import the connector file, I'm making this a regular import.
Will give them a test package to verify the issue is resolved
=> [RN] Use regular import for coinbase connector

.changeset/lazy-cougars-explode.md, packages/sdk/.eslintrc.cjs, packages/sdk/src/evm/core/classes/contract-events.ts, packages/sdk/src/evm/core/classes/factory.ts, packages/sdk/src/evm/core/sdk.ts, packages/wallets/.eslintrc.cjs
Fixes #1535 - Named export 'EventEmitter' not found in Nuxt/Vite with yarn
=> [sdk] Use default import for EventEmitter

.changeset/cuddly-peas-appear.md, packages/storage/src/core/downloaders/storage-downloader.ts, packages/storage/src/types/download.ts
Timeouts of 30s was getting hit in some legit cases, but global option to override wasn't exposed
=> [Storage] Up default download timeout to 60s, expose option to override it

.changeset/tidy-hairs-drive.md, packages/sdk/src/evm/common/gas-price.ts, packages/sdk/src/evm/constants/chains/supportedChains.ts, packages/sdk/src/evm/core/classes/contract-wrapper.ts, packages/sdk/src/evm/core/classes/gas-cost-estimator.ts, packages/sdk/src/evm/core/classes/transactions.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/base-api.ts
We were relying on hardcoded gas fees for most chains, this PR introduces a centralized method to compute gas fees and prioritizes `eth_maxPriorityFeePerGas` from the RPC directly to estimate fees accurately.
=> [SDK] Dynamic gas fee estimation

.changeset/cuddly-boats-sip.md, packages/contracts-js/package.json, packages/sdk/src/evm/core/classes/airdrop-erc1155.ts, packages/sdk/src/evm/core/classes/airdrop-erc20.ts, packages/sdk/src/evm/core/classes/airdrop-erc721.ts, pnpm-lock.yaml
Update airdrop function names on contracts and sdk to resolve abi conflict (https://github.com/thirdweb-dev/contracts/pull/496)
=> Airdrop abi conflict resolution

.changeset/afraid-moons-travel.md, packages/sdk/src/evm/common/gas-price.ts, packages/sdk/src/evm/core/classes/erc-1155-standard.ts, packages/sdk/src/evm/core/classes/erc-1155.ts, packages/sdk/src/evm/core/wallet/user-wallet.ts
`sdk.wallet.sendRawTransaction()` was not handling gas values for networks like Polygon and OP chains.
=> Handle default gas values for raw transactions, expose from property for 1155 airdrops

.changeset/nine-queens-pay.md, packages/sdk/src/evm/common/gas-price.ts
`getDefaultGasOverrides()` returning incorrect value.
=> fix: Typo on setting maxFeePerGas

packages/service-utils/src/cf-worker/usage.ts
evmMethod is useful metadata to track for certain services like RPC.
Method arguments are not tracked.
=> chore: add evmMethod to usage traacker body

packages/service-utils/src/cf-worker/index.ts, packages/service-utils/src/node/index.ts
Uncaught exceptions in logging may cause Express servers to crash.
- Add a try/catch to `logHttpRequest`. No user-facing impact.
=> fix: try/catch logHttpRequest

.changeset/red-years-clean.md, packages/sdk/src/evm/core/sdk.ts
- If you pass `network` to `ThirdwebSDK.fromSigner` it should always overwrite the network of the SDK and signer.
- Previously, if you pass `network` to `fromSigner`, but the `signer` passed in already has a configured `provider`, we wouldn't overwrite the network.
- Now we properly overwrite the network here.
=> [SDK] [Bug] Always update network if configured in fromSigner

.changeset/strange-planets-nail.md, packages/react/src/wallet/wallets/paper/PaperOTPLoginUI.tsx, packages/wallets/package.json, pnpm-lock.yaml
Previous implementation does not show the recovery screen modal for `USER_MANAGED` wallets in the headless flow
=> fix(react): show recovery password modal for `USER_MANAGED` in `paperWallet`

.changeset/pink-pianos-roll.md, packages/sdk/src/evm/core/classes/account.ts
Write functions for the `account` extension were written without enabling the `.prepare` functionality.
-  Enabled `.prepare` on all `account write functions
=> [SDK] Add support for prepare to account extension

.changeset/clever-gifts-love.md, packages/sdk/src/evm/core/classes/erc-20.ts
This is a subset of the changes from the draft PR below. Since https://github.com/thirdweb-dev/js/pull/1648 contains too many changes I will split it up into smaller PRs
=> [SDK] Various improvement to data fetching in erc-20.ts

.changeset/brown-moose-sniff.md, packages/sdk/src/evm/common/feature-detection/resolveContractUriFromAddress.ts
Expose `resolveImplementation()` helper function to resolve implementation address + bytecode of any proxy contract
=> [SDK] Expose proxy resolver helper function

.changeset/five-mice-complain.md, packages/sdk/src/evm/core/classes/transactions.ts
On certain RPC providers, checking for tx receipt right after a gasless call would throw, then eventually resolve. Added a try catch in the exponential retry loop.
=> [SDK] Fix error waiting for transaction after gasless tx

.changeset/tall-balloons-breathe.md, packages/sdk/test/evm/nft.test.ts
Add unit test for ERC721 allOwners() to ensure it does not return `AddressZero` as the owner
@jnsdls @joaquim-verges I'm practicing writing unit tests. Let me know whether this is encouraged or unecessary.
The function targeted for unit test:
path: `packages\sdk\src\evm\core\classes\erc-721-supply.ts`
```
/**
* Return all the owners of each token id in this contract
* @returns
*/
public async allOwners() {
let totalCount: BigNumber;
let startTokenId = BigNumber.from(0);
if (hasFunction<OpenEditionERC721>("startTokenId", this.contractWrapper)) {
startTokenId = await this.contractWrapper.read("startTokenId", []);
}
try {
totalCount = await this.erc721.totalClaimedSupply();
} catch (e) {
totalCount = await this.totalCount();
}
totalCount = totalCount.add(startTokenId);
// TODO use multicall3 …
```
=> [SDK] Add unit test for ERC721 allOwners()

.changeset/calm-comics-wash.md, .changeset/unlucky-hornets-ring.md, packages/sdk/src/evm/core/classes/contract-wrapper.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/base-api.ts
first SW transaction can run out of gas due to how we estimate gas for non deployed accounts. Added a 20% buffer to remediate, can probably be more accurate but this will help for now.
=> [SmartWallets] Fix gas estimation for first SW transaction

.changeset/red-seahorses-train.md, packages/react/src/design-system/index.ts, packages/react/src/wallet/ConnectWallet/Details.tsx, packages/react/src/wallet/ConnectWallet/ReceiveFunds.tsx
- Always show "Connected to Smart Wallet" text in ConnectWallet dropdown but only link to dashboard if it is deployed
- Show QR code in the Receive funds screen on mobile too
=> [react] ConnectWallet UI improvements

.changeset/olive-waves-draw.md, packages/sdk/src/evm/common/nft.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/nft-drop.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/signature-drop.ts
=> [SDK] Concurrent requests for NFT-related code

.changeset/old-students-work.md, packages/service-utils/src/cf-worker/usage.ts
Don't require account ID when publishing usage events. The internal analytics service will hydrate client ID -> account metadata.
- Make accountId optional when publishing usage events.
=> chore: Make accountId optional in usage event type

.changeset/cuddly-gorillas-cheer.md, packages/sdk/src/evm/core/classes/registry.ts
=> [SDK] Improve add/removeContract method for registry.ts

.changeset/empty-readers-grab.md, packages/wallets/src/evm/connectors/smart-wallet/index.ts, packages/wallets/src/evm/wallets/smart-wallet.ts
You can get a type error if you try to match a erc721 claim with another regular tx because erc721 claim returns an array of tx responses, which breaks the type checking.
=> [Wallets] Fix executeBatch type mismatch

.changeset/pretty-toys-yawn.md, packages/sdk/src/evm/constants/urls.ts, packages/sdk/src/evm/core/sdk.ts
RPC Override logic on SDK was not using the user provided RPC Url.
Supported Chain (RPC Override) Data:
```
[
{
"name": "Localhost",
"chain": "ETH",
"rpc": ["http://localhost:8000"],
"nativeCurrency": {
"name": "Ether",
"symbol": "ETH",
"decimals": 18
},
"chainId": 1337,
"shortName": "local",
"slug": "localhost"
}
]
```
=> RPC Override Fix

.changeset/wise-emus-cheer.md, packages/react-native/src/evm/components/ConnectWalletFlow/ConnectWalletFlow.tsx
When a single wallet is passed as a `supportedWallet` we auto-connect the wallet to save users one interaction. In the case where wallets needed to show a UI before connection (like the input text to get the email for embeddedWallet), we were bypassing showing this UI.
We now correctly check if the wallet has a `selectUI` or `connectUI` that needs to be shown before auto-connecting a single wallet.
Pass only one wallet with a selectUI as a supportedWallet: e.g. `embeddedWallet()`
=> [RN] Show selectUI component when passing one supportedWallet

.changeset/mean-lamps-tap.md, packages/react-core/src/evm/hooks/async/nft.ts
Context: https://github.com/thirdweb-dev/js/pull/1695
=> [React/React Native] Add pagination to useOwnedNFTs

.changeset/friendly-suns-laugh.md, packages/sdk/src/evm/common/any-evm-utils/fetchPublishedContractFromPolygon.ts
=> [SDK] Perf improve to `fetchPublishedContractFromPolygon()`

.changeset/gentle-countries-juggle.md, packages/sdk/src/evm/common/any-evm-utils/getDeploymentInfo.ts
=> [SDK] Perf improv for getDeploymentInfo

.changeset/sixty-taxis-train.md, packages/react/src/components/OTPInput.tsx
https://linear.app/thirdweb/issue/DEVX-1410/input-issues-for-otp-on-mobile
=> [react] - Fix OTP input not working well with Japanese keyboard

.changeset/nervous-students-warn.md, packages/wallets/evm/wallets/async/package.json, packages/wallets/package.json, packages/wallets/src/evm/wallets/async.ts
- Adds an `AsyncWallet` class that allows you to pass in a `getSigner` function that will get called when signer is actually needed.
- We need this in engine since the admin wallet can get created during runtime.
- You can configure `cacheSigner` to set whether the signer get's cached after the first use or not.
=> [Wallets] Add AsyncWallet

.changeset/fair-bikes-attend.md, packages/sdk/src/evm/contracts/prebuilt-implementations/marketplace.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/multiwrap.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/pack.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/split.ts, packages/sdk/src/evm/contracts/prebuilt-implementations/vote.ts
=> Improve performance for /prebuilt-implementations

.changeset/new-books-notice.md, .changeset/olive-impalas-knock.md, packages/sdk/src/evm/common/index.ts, packages/sdk/src/evm/common/plugin/getCompositePluginABI.ts, packages/sdk/src/evm/contracts/index.ts, packages/sdk/src/evm/core/sdk.ts, packages/sdk/src/evm/functions/getContractFromAbi.ts, packages/wallets/src/evm/connectors/smart-wallet/index.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/account.ts, packages/wallets/src/evm/wallets/smart-wallet.ts
added functions to send raw transactions + send versions of the current ones to not wait for tx
=> [SmartWallet] expose new send/execute smart wallet functions

.changeset/famous-penguins-lay.md, packages/wallets/src/evm/connectors/smart-wallet/lib/erc4337-provider.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/erc4337-signer.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/utils.ts
You can now chain send transactions without waiting for confirmations on smart wallets
=> [SmartWallet] implement multidimensional nonces for smart wallets

.changeset/moody-points-serve.md, packages/sdk/src/evm/core/classes/erc-1155-signature-mintable.ts
=> [SDK] Perf improvement for erc-1155-signature-mintable

.changeset/tame-snakes-retire.md, packages/wallets/src/evm/connectors/smart-wallet/lib/utils.ts
=> Use BigInt function instead of bigint primitive numbers

.changeset/short-beds-hunt.md, packages/wallets/src/evm/connectors/smart-wallet/utils.ts
Added the missing empty data arg `0x` to `isSmartWalletDeployed` logic's call to `accountFactory.getAddress`
=> Patch: missing data arg in isSmartWalletDeployed

.changeset/proud-buses-matter.md, packages/wallets/src/evm/connectors/embedded-wallet/implementations/lib/auth/abstract-login.ts, packages/wallets/src/evm/connectors/embedded-wallet/implementations/lib/auth/base-login.ts, packages/wallets/src/evm/connectors/embedded-wallet/implementations/lib/auth/index.ts, packages/wallets/src/evm/connectors/embedded-wallet/index.ts, packages/wallets/src/evm/connectors/embedded-wallet/types.ts
```
const embeddedWalletConnector = new EmbeddedWalletConnecter({
clientId: "Thirdweb client id",
chains: [Optimism, Goerli, Ethereum],
chain: Optimism,
});
embeddedWalletConnector.connect({
loginType: "custom_jwt_auth",
jwt: "Your jwt here",
encryptionKey: "Super strong encryption key",
});
```
=> [SDK] Custom jwt for embedded wallets

.changeset/metal-moles-press.md, packages/sdk/src/evm/common/sharded-merkle-tree.ts
clean up the base URI if it has a trailing slash
=> [SDK] Fix double trailing slash when downloading merkle data

.changeset/cuddly-kings-listen.md, packages/wallets/src/evm/connectors/smart-wallet/index.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/account.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/base-api.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/erc4337-provider.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/erc4337-signer.ts, packages/wallets/src/evm/wallets/smart-wallet.ts
Expose function to estimate SmartWallet transactions, handling pre and post deployment state
```ts
const cost = smartWallet.estimate(preparedTx);
const costBatch = smartWallet.estimateBatch(preparedTxs);
```
Also works with raw transactions
```ts
const cost = smartWallet.estimateRaw(rawTx);
const costBatch = smartWallet.estimateBatchRaw(rawTxs);
```
returns:
```ts
batch {
ether: '0.0000000000122901',
wei: BigNumber { _hex: '0xbb8834', _isBigNumber: true },
details: {
deployGasLimit: BigNumber { _hex: '0x0421b6', _isBigNumber: true },
transactionGasLimit: BigNumber { _hex: '0x053eb3', _isBigNumber: true },
gasPrice: BigNumber { _hex: '0x14', _isBigNumber: true },
transactionCost: BigNumber { _hex: '0x68e5fc', _isBigNumber: true },
deployCost: BigNumber { _hex: '0x52a238', _isBigNumber: …
```
=> [SmartWallet] Expose new estimation functions for smart wallet transactions

.changeset/new-poems-exercise.md, packages/wallets/src/evm/connectors/smart-wallet/utils.ts
Utility functions to get addresses were not letting you pass your optional salt
=> [SmartWallet] expose data in smart wallet utils

.changeset/smart-pens-tap.md, packages/react/src/wallet/ConnectWallet/ConnectWallet.tsx
It is possible for the user address and the active wallet address to be mismatched in ConnectWallet. This will cause the auth login endpoint will never be called, and result in bad auth behavior in the developer's application.
Examples of how this can happen:
- Create local wallet, then reload. The local wallet will still exist in storage (and recognized in useUser) but not recognized in useAddress.
- Force show the Sign In button if addresses are out of sync
=> Show sign in button if user address and active wallet address are mis-matched

.changeset/fair-ladybugs-rhyme.md, packages/react-native/src/evm/index.ts, packages/react-native/src/evm/wallets/connectors/embedded-wallet/embedded-connector.ts, packages/react-native/src/evm/wallets/hooks/useEmbeddedWalletSendVerificationEmail.ts, packages/react-native/src/evm/wallets/hooks/useSmartWallet.ts, packages/react/src/evm/hooks/useEmbeddedWalletSendVerificationEmail.ts, packages/react/src/evm/hooks/wallets/useSmartWallet.ts, packages/react/src/evm/index.ts
New API for conveniently connecting smart wallets without UI components:
Example with metamask:
```tsx
const { connect } = useSmartWallet(metamaskWallet(), {
factoryAddress: factoryAddress,
gasless: true,
});
const onClick = async () => {
// nothing to do here, all handled internally
await connect(); 
}
```
Example with localWallet:
```tsx
const { connect } = useSmartWallet(localWallet(), {
factoryAddress: factoryAddress,
gasless: true,
});
const onClick = async () => {
// function to 'load' the local wallet before using it
await connect({
connectPersonalWallet: async (w) => {
await w.generate();
await w.connect();
}
});
}
```
Example with embeddedWallet:
```tsx
const { connect } = useSmartWallet(embeddedWallet(), {
factoryAddress: factoryAddress,
gasless: true,
});
const onClick = async …
```
=> [SmartWallet] Improved `useSmartWallet` hook

.changeset/eight-carrots-confess.md, packages/auth/src/fastify/routes/login.ts
The response payload for the `/login` route in the Fastify Auth package is missing the `token` field, which is included in the Express and Next versions. This makes it incompatible with the `useLogin` hook from the `react` package: https://github.com/thirdweb-dev/js/blob/main/packages/react-core/src/evm/hooks/auth/useLogin.ts#L77
1. Fastify `/login` response changed from `{ success: true }` to `{ token: ... }`
1. Create Fastify auth example project
2. Integrate `useLogin` on the frontend
3. Print response of `login` function call, should now include `token` result
=> [auth] update fastify login route response to match express/next

.changeset/healthy-trains-deny.md, packages/react-core/src/evm/hooks/async/nft.ts, packages/react-core/src/evm/utils/cache-keys.ts
The code below doesn't work beecause currently they all share the same cacheKey, so as the result all of them will return the cached data from the first `useTotal...` (tokenId #0)
This fix adds the `tokenId` as the extra cacheKey
```
const { contract: nftContract } = useContract(
"0x8a41F6......9829659526"
);
const { data: token0 } = useTotalCirculatingSupply(nftContract, 0);
const { data: token1 } = useTotalCirculatingSupply(nftContract, 1);
const { data: token2 } = useTotalCirculatingSupply(nftContract, 2);
const { data: token3 } = useTotalCirculatingSupply(nftContract, 3);
console.log({
token0: token0?.toString(),
token1: token1?.toString(),
token2: token2?.toString(),
token3: token3?.toString(),
});
```
=> [React-core] Fix caching issue with useTotalCirculatingSupply

.changeset/rude-horses-shake.md, packages/service-utils/src/core/api.ts
Fixing a potential edge case where the response body is read twice, causing an unrelated throw:
```
Body has already been used. It can only be used once. Use tee() first if you need to read it twice.
```
=> fix: Reuse response body in service utils helper

.changeset/real-bags-marry.md, packages/wallets/src/evm/connectors/embedded-wallet/index.ts, packages/wallets/src/evm/connectors/embedded-wallet/types.ts
There was a potential code path that would attempt to get the signer after autoconnect where the user is not in the initialized state, resulting in getAddress returning the last saved address but the signer failing to initialize. Fixed that by enforcing that getUser() always returns a initialized user or throw, and syncing the getAddress() and getSigner() calls.
=> [Wallets] Fix potential embedded wallet autoconnect race condition

.changeset/smart-ligers-relax.md, packages/wallets/src/evm/connectors/embedded-wallet/index.ts
throw when users are in logged out or uninitialized states and attempting to get a signer
=> [Wallets] Enforce authenticated users when getting EW signers

.changeset/nasty-pears-pay.md, packages/unity-js-bridge/src/thirdweb-bridge.ts
- Added Apple and Facebook login to Unity WebGL bridge
- Updated to match C# API
- Set client id and build [this branch](https://github.com/thirdweb-dev/unity-sdk/pull/126) to WebGL
- Select one of the new social options
=> [Unity] Apple and Facebook logins

.changeset/olive-readers-marry.md, packages/sdk/src/evm/core/classes/contract-wrapper.ts, packages/sdk/src/evm/core/classes/transactions.ts
- Add support for polygon native `executeMetaTransaction` relayer method
=> Add support for executeMetaTransaction

.changeset/gold-parents-move.md, packages/unity-js-bridge/src/thirdweb-bridge.ts
Support smart wallet account override connect option
=> [Unity] SW Account Override Support

.changeset/fast-bags-attend.md, packages/service-utils/src/core/authorize/index.ts
API key cache TTL was computed wrongly when converted to MS.
=> fix: api key caching ttl

.changeset/wild-tigers-design.md, packages/react-core/src/core/providers/thirdweb-wallet-provider.tsx
* Connect a smart / safe wallet
* click on switch to personal wallet in the ConnectWallet dropdown
* reload the page
* expect to be connected to the last connected wallet ( personal wallet )
* problem: autoconnection fails because given personal wallet can not be found in the list of supported wallets in thirdweb provider
* if the last connected wallet is a personal wallet, get the personal wallet from smart wallet / safe wallet's personalWallets array and connect to it
=> [react-core] Fix auto-connecting a personal wallet for smart/safe wallet

.changeset/old-cycles-travel.md, packages/storage/src/common/urls.ts, packages/storage/src/common/utils.ts
User recorded this error:
https://github.com/thirdweb-dev/js/assets/26052673/dfecb175-7b91-47b7-9e66-5153f5910b9d
This happens because they have an NFT with an invalid IPFS uri
So we need catch the error causing by `CIDTool.base32(hash)`
=> [Storage] Catch error when converting invalid IPFS URIs

.changeset/proud-wombats-shake.md, packages/react/src/wallet/wallets/embeddedWallet/types.ts
Revert type change done in https://github.com/thirdweb-dev/js/commit/61c62b3f07a082ffd7620c949e3bcc6b75c104b5 for `EmbeddedWalletConfigOptions`
=> [react] Fix EmbeddedWalletConfigOptions type

.changeset/spotty-lizards-yawn.md, packages/wallets/src/evm/connectors/smart-wallet/index.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/base-api.ts, packages/wallets/src/evm/connectors/smart-wallet/utils.ts
- respect `value` when doing tx estimations
- add `getUserOpReceipt` utility function to get trasaction hashes from a userOp hash
=> [Wallets] Respect `value` in smart wallet gas estimations + add `getUserOpReceipt` utility function

.changeset/smooth-paws-cry.md, packages/wallets/src/evm/connectors/smart-wallet/lib/erc4337-signer.ts
Add support for `signTransactions` on `ERC4337Signer` so that users can store a signed user operation to broadcast later.
=> [Wallets] Add support for signTransaction for smart wallets

.changeset/swift-rockets-brake.md, packages/react-native/src/evm/wallets/wallets/wallet-connect/WalletConnectUI.tsx
=> [RN] Hide back button in WC modal when WC is the only supportedWallet

.changeset/stupid-toes-pull.md, packages/react-core/src/evm/hooks/async/token.ts, packages/react-core/src/evm/index.ts, packages/react-core/src/evm/utils/cache-keys.ts
Users have been asking about a react hook for transferring native token
=> [react-core] Add hook: useTransferNativeToken

.changeset/proud-mirrors-tease.md, packages/react-native/package.json, packages/react-native/src/evm/wallets/hooks/useCoinbaseWalletListener.ts, pnpm-lock.yaml
There's a listener that handles CoinbaseWallet's deeplinks. This listener calls a static function of the Coinbase wallet SDK called `handleResponse` to manage the deeplinks.
The `handleResponse` static function had a bug when checking if the Coinbase SDK was already instantiated ([Fix here](https://github.com/MobileWalletProtocol/wallet-mobile-sdk/pull/280). Since we only initialize the CoinbaseWallet once a user connects to it, opening the app from the deeplink was crashing if the Coinbase wallet was not connected.
We alerted Coinbase, they applied the fix and we updated their package
=> [RN] Update coinbase wallet SDK to fix scheme bug

packages/react/src/wallet/ConnectWallet/defaultTokens.ts
Changed the mapping of Avalanche tether USD contract address
- [x ] Internal API changes: explain the internal logic changes
No logic change, just changed address in the SupportedTokens data object
- [x ] Manual tests: step by step instructions on how to test
Connect to Avalanche in Connect component, go to "send" and see that Tether USD shows balance from correct contract address
=> changing Avalanche tether USD address mapping

.changeset/dull-pumpkins-provide.md, packages/react-native/src/evm/components/ConnectWallet.tsx, packages/react-native/src/evm/components/ConnectWalletDetails/ConnectWalletDetailsModal.tsx, packages/react-native/src/evm/components/ConnectWalletDetails/WalletDetailsButton.tsx, packages/react-native/src/evm/components/ReceiveButton.tsx
Devs are now able to hide the Send and/or Receive buttons:
Both props default to `false`.
```js
<ConnectWallet hideReceiveButton={true} hideSendButton={true} />
```
Devs can alternatively change the text of the buttons by customizing the locale object for the modal component:
```javascript
import { en, ThirdwebProvider } from '@thirdweb-dev/react-native';
<ThirdwebProvider
locale={en({
common: {
send: 'Deliver',
receive: 'Receive',
},
})}
...
```
=> [RN] Adds hideSendButtonand hideReceiveButton to ConnectWallet

.changeset/little-hats-hide.md, packages/react-native/src/evm/components/ConnectWalletFlow/ConnectWalletFlow.tsx, packages/react-native/src/evm/components/ConnectWalletFlow/SmartWallet/SmartWalletFlow.tsx, packages/react-native/src/evm/components/base/modal/TWModal.tsx, packages/react-native/src/evm/index.ts, packages/react-native/src/evm/wallets/wallets/wallet-connect/WalletConnectUI.tsx
You can now trigger the WC modal from your app without having to use the ConnectWallet button
```
import { WalletConnectUI } from "@thirdweb-dev/react-native";
<WalletConnectUI
hide={() => setWCModalVisible(false)}
connected={() => setWCModalVisible(false)}
walletConfig={supportedWallets[0]}
supportedWallets={supportedWallets}
isVisible={wcModalVisible}
projectId="your-wallet-connect-projectId"
/>
```
=> [RN] Export WC modal component

packages/wallets/src/evm/connectors/smart-wallet/index.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/base-api.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/erc4337-signer.ts, packages/wallets/src/evm/connectors/smart-wallet/types.ts, packages/wallets/src/evm/wallets/smart-wallet.ts
Updates #2113
Allow enabling/disabling gasless tx on demand.
- Initialize a smart wallet with gasless enabled or disabled
- Pass opposite `gasless` flag to transaction
=> feat: allow enabling/disabling gasless tx on demand

packages/wallets/test/smart-wallet-integration.test.ts
=> [Wallets] skip integration test if no secret key

packages/react-core/src/evm/hooks/async/nft.ts
Added Example for `useOwnedNFTs` hook for `queryParams` for paginating
=> Add: Example for useOwnedNFTs hook for queryParams

.changeset/smart-ads-draw.md, packages/react-native/src/evm/components/ConnectWalletFlow/ChooseWallet/ChooseWallet.tsx, packages/react-native/src/evm/components/ConnectWalletFlow/ConnectEmbed.tsx, packages/react-native/src/evm/components/ConnectWalletFlow/ConnectWalletButton.tsx, packages/react-native/src/evm/components/ConnectWalletFlow/ConnectingWallet/ConnectingWallet.tsx, packages/react-native/src/evm/components/ConnectWalletFlow/ConnectingWallet/ConnectingWalletHeader.tsx, packages/react-native/src/evm/components/MainModal.tsx, packages/react-native/src/evm/components/base/WalletButton.tsx, packages/react-native/src/evm/index.ts, packages/react-native/src/evm/providers/ui-context-provider.tsx, packages/react-native/src/evm/utils/modalTypes.ts
Devs can now show the Connect modal UI directly into their apps.
This component will render the wallets defined in our ThirdwebProvider.
```tsx
<ConnectEmbed
modalTitleIconUrl="<my-icon-url>"
modalTitle="Sign In"
theme={"light"}
onConnect={() => {
console.log("wallet connected");
}}
container={{
paddingVertical: "md",
marginHorizontal: "md",
borderRadius: "md",
}}
/>
```
=> [RN] Exports ConnectEmbed as a standalone component

.changeset/clever-shoes-help.md, packages/sdk/src/evm/common/any-evm-utils/fetchAndCacheDeployMetadata.ts, packages/sdk/src/evm/common/metadata-resolver.ts, packages/sdk/src/evm/common/utils.ts, packages/sdk/src/evm/functions/utils/cache.ts
bounded instead of unbounded caches for metadata + contract instances
=> [SDK] switch to LRU caches

.changeset/shaggy-frogs-add.md, packages/sdk/src/evm/core/classes/erc-1155.ts, packages/sdk/src/evm/core/classes/internal/erc1155/erc-1155-standard.ts, packages/sdk/test/evm/custom.test.ts
Exposes erc1155.transferBatch API
=> [SDK] Add erc1155.transferBatch

.changeset/cool-planets-help.md, packages/unity-js-bridge/src/thirdweb-bridge.ts, packages/wallets/src/evm/connectors/smart-wallet/index.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/erc4337-signer.ts, packages/wallets/src/evm/connectors/smart-wallet/types.ts
Allow users to specify whether they want to force deploy smart wallets on sign, useful in cases where delayed deploy is needed and only write tx should trigger it, such as session key creation or just avoiding spam.
=> [AA] Option to not deploy SW on sign message

.changeset/beige-fireants-invite.md, packages/react/src/evm/hooks/wallets/useSmartWallet.ts, packages/wallets/src/evm/wallets/smart-wallet.ts
=> [Docs] Document deployOnSign

.changeset/khaki-dots-cry.md, .changeset/stale-moose-tan.md, packages/service-utils/src/core/api.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/base-api.ts
Add option and types for policy checks
=> [ServiceUtils] Option to include policy checks

.changeset/dirty-camels-shave.md, packages/react-native/src/evm/wallets/connectors/embedded-wallet/embedded-connector.ts, packages/react-native/src/evm/wallets/connectors/embedded-wallet/embedded/auth.ts, packages/react-native/src/evm/wallets/connectors/embedded-wallet/embedded/helpers/api/fetchers.ts, packages/react-native/src/evm/wallets/connectors/embedded-wallet/embedded/helpers/constants.ts, packages/react-native/src/evm/wallets/wallets/embedded/EmbeddedWallet.ts
=> [RN] Adds ability to delete the ews active account

.changeset/healthy-horses-pull.md, packages/auth/src/next/router-app/index.ts
I just realized that when running the Next.js `build` script the below TS error is thrown. Next.js does not like the return type of the async handler function (the handler in which no arguments are passed).
And I think in the App Router there is no need for the handler with zero arguments. It seems that the below lines only make sense in Pages Router.
https://github.com/thirdweb-dev/js/blob/bdf60e98900cd08df0e28d5f4a624a1154f786a3/packages/auth/src/next/router-app/index.ts#L62-L65
```
frontend:build:  ✓ Compiled successfully
Linting and checking validity of types  ..Failed to compile.
frontend:build: 
frontend:build: app/api/auth/[...thirdweb]/route.ts
frontend:build: Type error: Route "app/api/auth/[...thirdweb]/route.ts" has an invalid export:
frontend:build:   "Promise<Response | …
```
=> fix(auth): Next.js App Router handler return type

.changeset/rich-walls-unite.md, packages/sdk/src/evm/common/feature-detection/extractMinimalProxyImplementationAddress.ts, packages/sdk/src/evm/common/feature-detection/resolveContractUriFromAddress.ts, packages/sdk/test/evm/feature-detection.test.ts
- adds another minimal proxy pattern
- updates `resolveImplementation` to return original address if implementation address returns 0x
=> Resolve implementation update

.changeset/clever-cows-fix.md, packages/react/src/wallet/wallets/xdefi/xdefiWallet.tsx
Update the code snippet so that it reflects in the docs
```Address: ```
=> [React] Update code snippet for XDEFI wallet

.changeset/good-ways-listen.md, packages/unity-js-bridge/src/thirdweb-bridge.ts, packages/wallets/src/evm/connectors/smart-wallet/index.ts, packages/wallets/src/evm/connectors/smart-wallet/lib/erc4337-signer.ts, packages/wallets/src/evm/connectors/smart-wallet/types.ts, packages/wallets/src/evm/wallets/abstract.ts, packages/wallets/src/evm/wallets/smart-wallet.ts, packages/wallets/test/smart-wallet-integration.test.ts
Support 712 based smart wallet signing and 1271 verification for new factories.
Remove optional deployment option.
Move smart-wallet signing functionality to erc4337-signer, all flows except user op signing should go through this.
```Address: ```
=> [Smart Wallet] Always force deploy on sign/auth, support 1271

.changeset/stale-papayas-mate.md, packages/sdk/src/evm/core/classes/erc-1155.ts, packages/sdk/test/evm/edition.test.ts
=> [SDK] handle updating metadata for ERC1155Token contracts

.changeset/dry-roses-cross.md, packages/thirdweb/src/react/core/hooks/contract/useReadContract.ts
This PR addresses the need for more flexible configuration options when using the `useReadContract` hook. By adding `refetchInterval` and `retry` parameters, users can customize the frequency of refetching data and the number of retry attempts on failure, respectively. These options improve the robustness and flexibility of the `useReadContract` hook when interacting with contracts.
=> Adds options refetchInterval and retry params to useReadContract

packages/thirdweb/src/constants/addresses.ts, packages/thirdweb/src/exports/thirdweb.ts
This PR refactors the constant `ADDRESS_ZERO` to `ZERO_ADDRESS` for better clarity and maintainability. The original `ADDRESS_ZERO` constant is retained but marked as deprecated.
- Renamed `ADDRESS_ZERO` to `ZERO_ADDRESS` in `packages/thirdweb/src/constants/addresses.ts`
- Updated exports in `packages/thirdweb/src/exports/thirdweb.ts` to include both `ADDRESS_ZERO` (deprecated) and `ZERO_ADDRESS`
- Ensure that all instances of `ADDRESS_ZERO` correctly map to `ZERO_ADDRESS`
- Check for any breaking changes in the application where `ADDRESS_ZERO` was previously used
The renaming provides better clarity and consistency in the codebase, aiding in maintainability and readability by clearly distinguishing the zero address constant.
=> refactor(constants): rename ADDRESS_ZERO to ZERO_ADDRESS and deprecate older name

.vscode/settings.json
Updated the VSCode settings to change the TypeScript auto import file exclude patterns.
Updated the `typescript.preferences.autoImportFileExcludePatterns` in `.vscode/settings.json` to exclude `./packages/thirdweb/src/exports` directory.
1. Open VSCode settings.
2. Verify that the `typescript.preferences.autoImportFileExcludePatterns` includes the `./packages/thirdweb/src/exports` pattern.
To ensure that TypeScript auto imports do not include files from the specified `./packages/thirdweb/src/exports` directory, preventing potential conflicts and reducing clutter in import suggestions.
---
=> [Chore] Update auto import file exclude patterns for TypeScript in .vscode settings

apps/dashboard/vercel.json, apps/playground-web/vercel.json
Add new `vercel.json` files to the dashboard and playground-web applications for enabling GitHub auto job cancellation.
Two new `vercel.json` files were created and added to the respective applications. These files contain configuration for automatically canceling previous jobs in GitHub actions when new commits are pushed.
1. Navigate to the dashboard and playground-web directories.
2. Check for the presence of the `vercel.json` files.
3. Ensure the config `
---
=> [Chore] Add Vercel configuration for auto job cancelation in dashboard and playground-web apps

apps/dashboard/src/components/contract-components/hooks.ts, packages/thirdweb/src/wallets/smart/smart-wallet-zksync.test.ts
we were sending eth_sendTransaction via the provider instead of the signer in the zksync wrapper (which will go away soon)
=> feat(wallet): handle eth_sendTransaction when doing zksync direct deploys

.changeset/ten-rockets-stare.md, packages/thirdweb/src/react/core/hooks/transaction/useSendTransaction.ts, packages/thirdweb/src/react/web/ui/ConnectWallet/screens/Buy/main/useBuyTxStates.ts, packages/thirdweb/src/transaction/utils.ts
=> fix: improve transaction cost estimation for pay modal

.changeset/fluffy-rings-kick.md, packages/thirdweb/src/react/core/hooks/connection/ConnectButtonProps.ts, packages/thirdweb/src/react/core/hooks/transaction/useSendTransaction.ts, packages/thirdweb/src/react/web/ui/ConnectWallet/screens/Buy/TransactionModeScreen.tsx, packages/thirdweb/src/react/web/ui/PayEmbed.tsx
=> [SDK] Fix: PayEmbed purchase callback and insufficient funds display

packages/thirdweb/src/analytics/track/pay.ts, packages/thirdweb/src/react/core/hooks/transaction/useSendTransaction.ts
Fixes: TOOL-3114
Anything important to call out? Be sure to also clarify these in your comments.
Unit tests, playground, etc.
=> [SDK] feat: Add pay event tracking for transaction modal states

apps/dashboard/redirects.js
Fixes: TOOL-3144
Updates redirects for `/create-api-key` and `/dashboard/settings` to point to `/team` instead of `/team/~/~/projects`
=> [Dashboard] fix: Update dashboard redirect paths to /team

apps/dashboard/src/@/api/chain.ts, apps/dashboard/src/@/constants/env.ts, apps/dashboard/src/app/(dashboard)/(chain)/utils.ts, apps/dashboard/src/app/login/auth-actions.ts
Implemented dynamic gas sponsorship detection for chains through a new API endpoint
- Added a new API endpoint to fetch gas-sponsored chains
- Removed hardcoded gas sponsorship flags from chain metadata
- Created reusable `getGasSponsoredChains` function with 15-minute cache
- Refactored chain metadata to dynamically apply gas sponsorship status and CTA
- Moved API secret to environment constants
1. Set up the `API_SERVER_SECRET` environment variable
2. Visit chain pages to verify gas sponsorship badges appear correctly
3. Confirm gas sponsorship CTAs display for supported chains
4. Verify the gas sponsorship status updates when chains are added/removed from the API response
Moving gas sponsorship configuration to an API endpoint allows for dynamic updates without code changes and …
=> fetch gas sponsored chains from API instead of hardcoding

apps/dashboard/src/app/team/[team_slug]/[project_slug]/connect/pay/webhooks/components/webhooks.client.tsx
Added `teamId` parameter to webhook creation and deletion API calls.
- Added `teamId` to the request payload when creating new webhooks
- Added `teamId` to the request payload when deleting existing webhooks
1. Navigate to the webhooks page for a project
2. Create a new webhook and verify it succeeds
3. Delete an existing webhook and verify it succeeds
4. Check server logs to confirm `teamId` is being received correctly
The `teamId` parameter is required for proper webhook management and authorization at the team level. This ensures webhooks are properly scoped to the correct team context.
=> add teamId parameter to webhook endpoints

apps/dashboard/framer-rewrites.js
Added new learn section routes to support the learning platform, including paths for tutorials, guides, courses, and glossary.
=> add /learn routes to framer rewrites

.changeset/mean-animals-eat.md, packages/thirdweb/src/react/web/ui/ConnectWallet/screens/Buy/BuyScreen.tsx, packages/thirdweb/src/react/web/ui/ConnectWallet/screens/Buy/swap/BuyTokenInput.tsx
=> [SDK] fix: Handle comma decimal input in PayEmbed

apps/playground-web/src/app/insight/insightBlueprints.ts
This PR makes the following changes to the insight blueprints:
- Renames "Get token transfers by wallet address" to "Get token transfers"
- Renames "Get NFT transfers by owner" to "Get NFT transfers"
- Adds a new endpoint "Get NFT balances by address" with path "/v1/nfts/balance/{ownerAddress}"
Verify the updated endpoint names and new NFT balances endpoint appear correctly in the dashboard.
=> update insight playground nav

apps/dashboard/src/components/settings/Account/Billing/planToTierRecord.ts, apps/dashboard/src/components/smart-wallets/SponsorshipPolicies/index.tsx
Updated plan tier hierarchy by swapping `starter` and `starter_legacy` positions, and lowered the required plan for sponsorship policies from `accelerate` to `starter`.
- Modified the plan tier hierarchy in `planToTierRecordForGating` by changing:
- `starter_legacy` from tier 1 to tier 2
- `starter` from tier 2 to tier 1
- Reduced the required plan for the sponsorship policies feature from `accelerate` to `starter` in the `GatedSwitch` component
1. Verify that users on the `starter` plan can now access sponsorship policies
2. Confirm that the plan hierarchy works correctly in all gated features
3. Test that users on `starter_legacy` plans maintain their expected access levels
This change makes sponsorship policies available to more users by lowering the tier requirement. The plan …
=> Update plan tier hierarchy for sponsorship policies

.changeset/config.json
This PR updates the `.changeset/config.json` file with the following changes:
- Reorganized the configuration properties in a more structured order
- Added "nebula-app" to the list of ignored packages
- Moved experimental unsafe options to the top of the file
- Maintained all existing configuration values and behavior
=> [Changeset] Add nebula-app to ignore list and reorder config

.changeset/cute-houses-own.md, apps/dashboard/src/@/storybook/stubs.ts, packages/service-utils/src/core/api.ts, packages/service-utils/src/mocks.ts
This PR adds the `gateway` capability to the team capabilities structure in the service-utils package. The gateway capability includes:
- `enabled` flag
- `rateLimit` property set to 1000 by default
The changes are implemented across:
- Service-utils core API types
- Mock data for testing
- Dashboard storybook stubs
A changeset has been added to track this patch update.
=> Add `gateway` team capabilities

apps/dashboard/next.config.ts
This PR updates the Content Security Policy in the dashboard app to:
- Add `us.posthog.com` to the `style-src` directive to allow styles from PostHog
- Add `framer.com` and `googletagmanager.com` to the `script-src` directive to allow scripts from Framer and Google Tag Manager
=> Add posthog.com and framer.com to CSP

apps/dashboard/framer-rewrites.js, apps/dashboard/redirects.js
Renamed "nebula" to "ai" in navigation paths and added a redirect from the old path to the new one.
- Updated the framer-rewrites.js file to change "/nebula" to "/ai" in the navigation paths
- Added a new redirect in redirects.js to automatically redirect users from "/nebula" to "/ai"
- Updated the comment in framer-rewrites.js from "-- nebula" to "-- ai" to reflect the name change
1. Verify that navigating to "/ai" loads the correct page
2. Verify that navigating to "/nebula" automatically redirects to "/ai"
3. Check that all functionality previously available at "/nebula" is working correctly at "/ai"
This change renames the "nebula" feature to "ai" to better reflect its purpose and functionality, making it more intuitive for users to find and understand the AI-related features of the …
=> Rename `/nebula` to `/ai` and add redirect

apps/dashboard/src/app/(app)/team/[team_slug]/(team)/TeamSidebarLayout.tsx
Always display the Chain Infrastructure section in the team sidebar, even when no chain subscriptions exist.
Modified the `TeamSidebarLayout.tsx` file to:
- Always render the Chain Infrastructure section in the sidebar instead of conditionally showing it only when chain subscriptions exist
- Added TODO comments to create overview pages for ecosystems and chains
- Added a separator before the infrastructure section to visually distinguish it from other sections
1. Navigate to a team page with no chain subscriptions
2. Verify that the Chain Infrastructure section appears in the sidebar
3. Check that the separator appears correctly before the infrastructure section
4. Confirm that teams with existing chain subscriptions still display correctly
This change improves UI consistency by always …
=> Always show Chain Infrastructure in sidebar regardless of subscriptions

apps/dashboard/src/@/hooks/useEngine.ts, apps/dashboard/src/app/(app)/team/[team_slug]/[project_slug]/(sidebar)/engine/(general)/overview/engine-instances-table.tsx, apps/dashboard/src/app/(app)/team/[team_slug]/[project_slug]/(sidebar)/engine/(general)/page.tsx, apps/dashboard/src/app/(app)/team/[team_slug]/[project_slug]/(sidebar)/engine/(instance)/[engineId]/configuration/components/engine-wallet-config.tsx, apps/dashboard/src/app/(app)/team/[team_slug]/[project_slug]/(sidebar)/engine/(instance)/[engineId]/layout.tsx, apps/dashboard/src/app/(app)/team/[team_slug]/[project_slug]/(sidebar)/engine/(instance)/[engineId]/metrics/components/EngineSystemMetrics.tsx, apps/dashboard/src/app/(app)/team/[team_slug]/[project_slug]/(sidebar)/engine/(instance)/[engineId]/overview/components/create-backend-wallet-button.tsx, apps/dashboard/src/app/(app)/team/[team_slug]/[project_slug]/(sidebar)/engine/(instance)/[engineId]/overview/components/engine-overview.tsx, apps/dashboard/src/app/(app)/team/[team_slug]/[project_slug]/(sidebar)/engine/(instance)/[engineId]/overview/components/import-backend-wallet-button.tsx, apps/dashboard/src/app/(app)/team/[team_slug]/[project_slug]/(sidebar)/engine/_utils/getEngineInstancePageMeta.ts
Updated URL paths for Engine instances by removing the "dedicated" segment from all routes.
- Removed the `/dedicated` segment from all Engine-related URL paths in API calls and internal links
- Updated API endpoint from `/v1/teams/${teamIdOrSlug}/${projectSlug}/engine/dedicated/${engineId}/metrics` to `/v1/teams/${teamIdOrSlug}/${projectSlug}/engine/${engineId}/metrics`
- Updated all internal navigation links to use the simplified path structure
- Modified redirect paths to match the new URL pattern
1. Navigate through the Engine UI and verify all links work correctly
2. Test the import functionality with the new URL structure
3. Verify API calls for metrics and other Engine-related endpoints function properly
4. Check that all redirects work as expected, especially for login redirects …
=> Remove "dedicated" from Engine URLs

apps/dashboard/src/@/constants/server-envs.ts
Temporarily removed tainting of `GROWTH_PLAN_SKU` and `PAYMENT_METHOD_CONFIGURATION` environment variables to allow client-side access. Added a comment to indicate these values should not be tainted for now.
=> Remove taint from GROWTH_PLAN_SKU and PAYMENT_METHOD_CONFIGURATION

apps/dashboard/framer-rewrites.js
Added a new rewrite rule for the `/payments/x402` path in the dashboard app.
Added `/payments/x402` to the list of rewrite paths in the `framer-rewrites.js` file. This allows the dashboard app to properly handle and route requests to this new payments path.
1. Navigate to the `/payments/x402` route in the dashboard app
2. Verify that the page loads correctly and follows the expected rewrite behavior
3. Ensure that existing payment routes continue to function as expected
This change supports a new payments feature or section identified as "x402" that needs to be accessible through the dashboard. Adding the rewrite rule ensures proper routing and functionality for this new payments path.
=> Add /payments/x402 to framer-rewrites
