thirdweb-dev/js

.changeset/few-otters-carry.md
packages/sdk/src/evm/common/feature-detection.ts

[SDK] Add check if abi exists

---

.changeset/lucky-foxes-suffer.md
packages/sdk/src/evm/core/classes/contract-wrapper.ts
packages/sdk/test/evm/gasless.test.ts

Issue ref: https://github.com/thirdweb-dev/ozdefender-autotask/issues/4#issuecomment-1272880337

[SDK] Fix multicall txns in a gasless setup

---

.changeset/thirty-houses-matter.md
packages/react/MIGRATION_GUIDE.md
packages/react/README.md
packages/react/src/evm/components/NftMedia.tsx
packages/react/src/evm/hooks/async/nft.ts
packages/react/src/evm/hooks/contracts/useEdition.ts
packages/react/src/evm/hooks/contracts/useEditionDrop.ts
packages/react/src/evm/hooks/contracts/useMarketplace.ts
packages/react/src/evm/hooks/contracts/useMultiwrap.ts
packages/react/src/evm/hooks/contracts/useNFTCollection.ts
packages/react/src/evm/hooks/contracts/useNFTDrop.ts
packages/react/src/evm/hooks/contracts/usePack.ts
packages/react/src/evm/hooks/contracts/useSignatureDrop.ts
packages/react/src/evm/hooks/contracts/useSplit.ts
packages/react/src/evm/hooks/contracts/useToken.ts
packages/react/src/evm/hooks/contracts/useTokenDrop.ts
packages/react/src/evm/hooks/contracts/useVote.ts

Found some docs that were wrong but especially the deprecation notices, those didn't make sense

[React] Docs update

---

.changeset/long-sloths-reflect.md
packages/react/src/evm/components/shared/Button/index.tsx
packages/react/src/evm/components/shared/Menu/Menu.tsx

Fixes #85 to make @jarrodwatts a happy dev <3

[REACT] Fix Border Radius for Safari

---

.changeset/moody-pumas-grow.md
packages/react/src/components/Tooltip.tsx
packages/react/src/evm/index.ts
packages/react/src/wallet/ConnectWallet/Details.tsx
packages/react/src/wallet/ConnectWallet/NetworkSelector.tsx
packages/react/src/wallet/hooks/useCanSwitchNetwork.ts
packages/wallets/src/evm/interfaces/tw-connector.ts

Fixes 
* Switch Network UI not working in Network Selector
* When changing network / account in extension UI is not updating 
* Confirm UI not showing up for wallet connect v1 and v2
* Tool tip z-index issue in UI

Cwv2 connection fixes

---

.changeset/silent-birds-greet.md
packages/sdk/src/evm/common/ens.ts

[SDK] Fix infinite recursion in ENS cache

---

.changeset/beige-plums-hug.md
packages/react-core/src/evm/hooks/auth/useLogout.ts

[RectCore] fix auth logout by invalidating and storing invalidated cookie

---

.changeset/famous-waves-hang.md
packages/react/src/wallet/ConnectWallet/Details.tsx
packages/react/src/wallet/ConnectWallet/NetworkSelector.tsx
packages/wallets/src/evm/connectors/metamask/index.ts
packages/wallets/src/evm/wallets/metamask.ts

[react] add switch account for MetaMask

---

.changeset/friendly-apes-wait.md
packages/unity-js-bridge/src/thirdweb-bridge.ts
packages/wallets/evm/wallets/device-walllet-node/package.json
packages/wallets/package.json
packages/wallets/src/core/AsyncJsonFileStorage.ts
packages/wallets/src/core/CredentialsStorage.ts
packages/wallets/src/evm/connectors/device-wallet/index.ts
packages/wallets/src/evm/index.ts
packages/wallets/src/evm/wallets/device-wallet.ts
packages/wallets/src/evm/wallets/device-walllet-node.ts
pnpm-lock.yaml
test/e2e/cra-5/package.json

spec : https://www.notion.so/thirdweb/Device-Wallet-8560342a54c84e5cb6f00af4924b5c35

[wallets] Device Wallet Revamp

---

packages/wallets/src/evm/wallets/device-wallet.ts

* fix the return type of `import` and `load` 
* fix dynamic import error of crypto-js on vite

[wallets] device wallet fixes 

---

.changeset/sweet-olives-provide.md
packages/react/src/components/DragNDrop.tsx
packages/react/src/components/Tooltip.tsx
packages/react/src/components/buttons.tsx
packages/react/src/components/formElements.tsx
packages/react/src/components/formFields.tsx
packages/react/src/components/modalElements.tsx
packages/react/src/evm/providers/wallet-ui-states-provider.tsx
packages/react/src/wallet/ConnectWallet/ConnectWallet.tsx
packages/react/src/wallet/ConnectWallet/Details.tsx
packages/react/src/wallet/ConnectWallet/NetworkSelector.tsx
packages/react/src/wallet/ConnectWallet/WalletSelector.tsx
packages/react/src/wallet/ConnectWallet/screens/ConnectingScreen.tsx
packages/react/src/wallet/ConnectWallet/screens/DeviceWallet/CreateDeviceWallet.tsx
packages/react/src/wallet/ConnectWallet/screens/DeviceWallet/DeviceWalletSetup.tsx
packages/react/src/wallet/ConnectWallet/screens/DeviceWallet/ExportDeviceWallet.tsx
packages/react/src/wallet/ConnectWallet/screens/DeviceWallet/ImportDeviceWallet.tsx
packages/react/src/wallet/ConnectWallet/screens/DeviceWallet/ReconnectDeviceWallet.tsx
packages/react/src/wallet/ConnectWallet/screens/DeviceWallet/RemoveWallet.tsx
packages/react/src/wallet/ConnectWallet/screens/DeviceWallet/common.tsx
packages/react/src/wallet/ConnectWallet/screens/DeviceWallet/useDeviceWalletInfo.ts
packages/react/src/wallet/ConnectWallet/screens/GetStartedScreen.tsx
packages/react/src/wallet/ConnectWallet/screens/GetStartedWithWallets.tsx
packages/react/src/wallet/ConnectWallet/screens/Safe/SafeForm.tsx
packages/react/src/wallet/ConnectWallet/screens/Safe/SelectPersonalWallet.tsx
packages/react/src/wallet/ConnectWallet/screens/Safe/Steps.tsx
packages/react/src/wallet/ConnectWallet/screens/ScanScreen.tsx

https://linear.app/thirdweb/issue/FTD-1661/device-wallet-ui-improvements
* Updated Device Wallet UI 
* Stop the keyboard popup on the network selector on mobile
* Fix the input not having the outline on iOS Safari for Safe Address

[react] Device wallet and other UI improvements

---

.changeset/perfect-oranges-fry.md
packages/sdk/src/evm/common/any-evm-constants.ts

Test contract deployment: https://thirdweb.com/theta-testnet/0x1828d922c3579182a6fe0b5f7bf29b12292711a4

[SDK] Custom gas-price for Theta testnet and mainnet

---

.changeset/mean-worms-enjoy.md
packages/react/src/wallet/wallets/localWallet/ExportLocalWallet.tsx
packages/wallets/src/evm/wallets/local-wallet.ts
packages/wallets/src/evm/wallets/magic.ts

- Fix type of connect() for magic wallet
- enforce smsLogin, emailLogin restriction for magic wallet
- update the icon for local wallet

[wallets] Magic and Local wallet improvements

---

.changeset/blue-eyes-move.md
packages/wallets/src/evm/connectors/paper/index.ts
packages/wallets/src/evm/wallets/base.ts

* Fix PaperWallet.connect() error
* Fix return type of Wallet.autoConnect()

[wallets] various fixes

---

.changeset/rich-mails-divide.md
packages/chains/chains/1243.ts
packages/chains/chains/1244.ts
packages/chains/chains/1452.ts
packages/chains/chains/155.ts
packages/chains/chains/1559.ts
packages/chains/chains/1777.ts
packages/chains/chains/1804.ts
packages/chains/chains/2606.ts
packages/chains/chains/338.ts
packages/chains/chains/418.ts
packages/chains/chains/71401.ts
packages/chains/chains/71402.ts
packages/chains/chains/8768.ts
packages/chains/src/index.ts
packages/sdk/src/evm/common/sharded-merkle-tree.ts
packages/sdk/src/evm/common/snapshots.ts

Zod parsing too many inputs at once causes a memory error

[SDK] Add chunked snapshot input parsing

---

.changeset/warm-boats-flow.md
packages/react/src/wallet/ConnectWallet/ConnectModal.tsx
packages/react/src/wallet/wallets/headlessConnectUI.ts
packages/react/src/wallet/wallets/localWallet/CreateLocalWallet.tsx
packages/react/src/wallet/wallets/localWallet/ReconnectLocalWallet.tsx
packages/react/src/wallet/wallets/localWallet/common.tsx
packages/react/src/wallet/wallets/magic/EmailConnect.tsx
packages/react/src/wallet/wallets/magic/MagicConnectUI.tsx
packages/react/src/wallet/wallets/magic/SMSConnect.tsx
packages/react/src/wallet/wallets/safe/SelectPersonalWallet.tsx
packages/react/src/wallet/wallets/smartWallet/SelectPersonalWallet.tsx
packages/react/src/wallet/wallets/smartWallet/SmartWalletConnecting.tsx
packages/wallets/src/evm/connectors/magic/types.ts

* skip wallet-selector screen if there's a single wallet
* Fix "Can't close Safe screen" issue
* Fix magic link config type

[react] Connect Wallet improvements

---

packages/react-native/src/evm/index.ts
packages/react-native/src/evm/wallets/wallets/trust-wallet.ts

- Expose all wallets for users to work with

[RN] Update wcv2 props

---

packages/react/src/evm/hooks/wallets/useSmartWallet.ts
packages/react/src/wallet/wallets/smartWallet/smartWallet.tsx
packages/react/src/wallet/wallets/smartWallet/types.ts

* expose all the config options of SmartWallet class from `smartWallet` configurator
* omit `chain` from `smartWallet` - that will be passed by react-core

[react] Fix smart wallet config type

---

.changeset/great-students-shop.md
packages/sdk/src/evm/common/deploy.ts
packages/sdk/src/evm/constants/addresses.ts
packages/sdk/src/evm/contracts/index.ts
packages/sdk/src/evm/core/classes/contract-deployer.ts
packages/sdk/src/evm/core/classes/factory.ts
packages/sdk/src/evm/core/sdk.ts
packages/sdk/src/evm/core/types.ts
packages/sdk/src/evm/functions/getContract.ts
packages/sdk/src/evm/functions/utils/cache.ts
packages/sdk/src/evm/functions/utils/contract.ts
packages/sdk/src/evm/index.ts
packages/sdk/src/evm/types/registry.ts

Cuts Circular deps from ~100 to ~50 !

[sdk] reduce circular deps

---

.changeset/grumpy-dogs-dance.md
packages/react/src/evm/hooks/wallets/useSmartWallet.ts
packages/react/src/wallet/ConnectWallet/Details.tsx
packages/react/src/wallet/wallets/localWallet/CreateLocalWallet.tsx
packages/react/src/wallet/wallets/localWallet/ExportLocalWallet.tsx
packages/react/src/wallet/wallets/localWallet/ImportLocalWallet.tsx
packages/react/src/wallet/wallets/localWallet/LocalWalletConnectUI.tsx
packages/react/src/wallet/wallets/localWallet/ReconnectLocalWallet.tsx
packages/react/src/wallet/wallets/localWallet/localWallet.tsx
packages/react/src/wallet/wallets/localWallet/overrideConfirmation.tsx
packages/react/src/wallet/wallets/localWallet/types.ts
packages/react/src/wallet/wallets/localWallet/useLocalWalletInfo.tsx
packages/react/src/wallet/wallets/safe/SelectAccount.tsx
packages/react/src/wallet/wallets/safe/SelectPersonalWallet.tsx
packages/react/src/wallet/wallets/safe/safeWallet.tsx
packages/react/src/wallet/wallets/safe/types.ts
packages/react/src/wallet/wallets/smartWallet/SelectPersonalWallet.tsx
packages/react/src/wallet/wallets/smartWallet/SmartWalletConnecting.tsx
packages/react/src/wallet/wallets/smartWallet/smartWallet.tsx
packages/react/src/wallet/wallets/smartWallet/types.ts

Fixes 
* https://linear.app/thirdweb/issue/FTD-1746/backing-up-a-wallet-without-it-being-connected-throws-an-error
* https://linear.app/thirdweb/issue/FTD-1745/backup-wallet-screen
and code cleanup - rename variables and types from "configuredWallet" to "walletConfig" naming

[react] Fix Local wallet backup 

---

.changeset/fast-ants-battle.md
packages/chains/data/additional/999.mjs
packages/chains/data/overrides/592.mjs
packages/chains/scripts/generate-package.mjs

- Add Zora Network to additional chains
Conflicts with another chain with Id 999 - we're overriding it, and adding Zora
**Note**: All chains in _additional chains_ will now override chains pulled from remote source
- Add public RPC for Astar network in overrides

[Chains] Update chains

---

.changeset/sweet-carrots-wonder.md
packages/sdk/.eslintrc.cjs
packages/sdk/src/evm/common/feature-detection/resolveContractUriFromAddress.ts
packages/sdk/src/evm/common/legacy.ts
packages/sdk/src/evm/common/metadata-resolver.ts
packages/sdk/src/evm/common/plugin/getCompositePluginABI.ts
packages/sdk/src/evm/common/plugin/getPluginABI.ts
packages/sdk/src/evm/common/snapshots.ts
packages/sdk/src/evm/common/verification.ts
packages/sdk/src/evm/constants/currency.ts
packages/sdk/src/evm/contracts/index.ts
packages/sdk/src/evm/core/classes/transactions.ts

* enable no-cycle rule
* various tree-shaking improvements

[sdk] Tree shaking improvements

---

.changeset/lucky-ads-compete.md
packages/cli/src/create/helpers/run-command.ts
packages/cli/src/lib/utils.ts

Revert Checking for pip and pip3

---

.changeset/slow-starfishes-yawn.md
packages/wallets/src/evm/connectors/safe/constants.ts
packages/wallets/src/evm/connectors/safe/index.ts
packages/wallets/src/evm/wallets/safe.ts

160kB improvement!
before: 
after:

[react] Fix safeWallet tree-shaking

---

.changeset/stupid-dryers-camp.md
packages/react/src/evm/hooks/wallets/usePaper.ts
packages/react/src/wallet/wallets/magic/magicLink.tsx
packages/react/src/wallet/wallets/paperWallet.tsx
packages/wallets/package.json
packages/wallets/src/evm/connectors/paper/index.ts
packages/wallets/src/evm/connectors/paper/types.ts
packages/wallets/src/evm/wallets/paper-wallet.ts
pnpm-lock.yaml

* expose advancedOptions and styles for paper wallet
* Allow using + in paper email
* Allow using + in magic email
* Update Paper SDK version

[wallets, react] expose advancedOptions in paper

---

.changeset/seven-jobs-carry.md
packages/chains/chains/1.ts
packages/chains/chains/10.ts
packages/chains/chains/137.ts
packages/chains/chains/420.ts
packages/chains/chains/421613.ts
packages/chains/chains/5.ts
packages/chains/chains/59140.ts
packages/chains/chains/80001.ts
packages/chains/scripts/generate-package.mjs
packages/chains/src/utils.ts

Fixes https://github.com/thirdweb-dev/js/issues/1242

[chains] Fix RPC override issue

---

.changeset/sharp-llamas-accept.md
packages/wallets/src/evm/connectors/smart-wallet/lib/erc4337-signer.ts
packages/wallets/src/evm/connectors/smart-wallet/lib/paymaster.ts

fix: handling authz errors from smart wallet connector

---

.changeset/shiny-hornets-whisper.md
.changeset/short-stingrays-promise.md
packages/react/src/wallet/wallets/InputSelectionUI.tsx
packages/react/src/wallet/wallets/metamask/metamaskWallet.tsx
packages/wallets/src/evm/connectors/metamask/getInjectedMetamaskProvider.ts
packages/wallets/src/evm/connectors/metamask/index.ts
packages/wallets/src/evm/index.ts
packages/wallets/src/evm/wallets/metamask.ts

* Stop auto focusing the paper/magic's email/phone input in ConnectWallet modal - because that opens up the keyboard on mobile which is very annoying
* Don't show Metamask as Installed when only the Phantom wallet is installed

[wallets, react] Various improvements 

---

.changeset/late-news-cover.md
packages/service-utils/src/core/authorize/client.test.ts
packages/service-utils/src/core/authorize/client.ts
packages/service-utils/src/core/authorize/index.ts
packages/service-utils/src/core/authorize/service.test.ts
packages/service-utils/src/core/authorize/service.ts

Updated the response messages on service utils to include more details and help user understand it.

Service Utils Response Updates

---

packages/chains/test/utils.test.ts

Add unit tests in `packages/chains/src/utils`.

add packages/chains/utils test

---

.changeset/eight-files-thank.md
packages/service-utils/src/cf-worker/usage.ts

Adds a `userOpHash` field to track bundler user operation hashes.

[service-utils] Add userOpHash field

---

.github/pull_request_template.md

We didnt have a common way to describe PRs (internal or external)
Added PR template
Once merged, open a new PR

[All] Added PR template

---

.changeset/seven-cows-love.md
.changeset/tiny-rats-brush.md
packages/sdk/src/evm/common/index.ts
packages/wallets/src/evm/connectors/smart-wallet/lib/base-api.ts

We werent estimating gas correctly for mumbai/polygon userOps

[Wallets] correct gas estimation for polygon/mumbai

---

.changeset/two-tips-cheat.md
packages/sdk/src/evm/common/any-evm-constants.ts

Custom gas price for Create2 factory deployment on Cronos Testnet

[SDK] Custom base fee for cronos testnet

---

.changeset/tidy-seals-own.md
packages/react-native/src/evm/components/ConnectWalletDetails/WalletDetailsButton.tsx
packages/react-native/src/evm/components/ConnectWalletDetails/WalletDetailsModalHeader.tsx
packages/react-native/src/evm/components/base/LoadingTextAnimation.tsx
packages/react-native/src/evm/components/base/TextBalance.tsx
packages/tw-tsconfig/react-native-library.json

1. Improve UI response when user presses disconnect
2. Add a loading state before fetching the wallet's balance

[RN] Improves loading states when disconnecting and loading balances

---

.changeset/wise-jokes-kiss.md
packages/sdk/src/evm/contracts/index.ts
packages/sdk/src/evm/core/classes/marketplacev3-english-auction.ts

There were some inefficiencies with the usage of Promise.all

Small fix for Promise.all()

---

.changeset/heavy-balloons-call.md
packages/chains/chains/100.ts
packages/chains/chains/14853.ts
packages/chains/chains/2221.ts
packages/chains/chains/2222.ts
packages/chains/chains/2323.ts
packages/chains/chains/2332.ts
packages/chains/chains/37.ts
packages/chains/chains/47.ts
packages/chains/chains/5234.ts
packages/chains/chains/75.ts
packages/chains/chains/8453.ts
packages/chains/data/additional/37.mjs
packages/chains/data/additional/47.mjs
packages/chains/src/index.ts

updated chains (including explicitly overriding (adding) `xpla` chain)

[chains] - add xpla chains & update chains

---

.changeset/hot-horses-chew.md
packages/sdk/src/evm/common/any-evm-utils/fetchPublishedContractFromPolygon.ts

Correct chain / polygon rpc for fetching published contract

[SDK] Correct polygon rpc for fetching published contract

---

packages/contracts-js/package.json
packages/sdk/src/evm/core/classes/pack-vrf.ts
pnpm-lock.yaml

Update contracts package version to v3.9.3-0.
Includes fix for Pack contract openPack (https://github.com/thirdweb-dev/contracts/pull/484)

Contracts version 3.9.3-0

---

.changeset/poor-poets-destroy.md
packages/chains/data/additional/88882.mjs

[Chains] Add Chiliz Spicy testnet

---

.changeset/perfect-fans-cough.md
packages/sdk/src/evm/common/any-evm-utils/computeDeploymentAddress.ts
packages/sdk/src/evm/common/any-evm-utils/getInitBytecodeWithSalt.ts
packages/sdk/src/evm/common/any-evm-utils/getSaltHash.ts

Check if bytecode is in correct format for deployment.

[SDK] Fix auto-factory deployment: correct bytecode format

---

.changeset/strange-balloons-help.md
packages/cli/src/create/command.ts
packages/cli/src/create/helpers/create-app.ts

npx thirdweb@nightly create --template pwa-vite-typescript-starter

[CLI] Adds support for PWA Vite template

---

.changeset/seven-rats-exist.md
packages/react/src/wallet/wallets/rainbow/RainbowConnectUI.tsx
packages/react/src/wallet/wallets/rainbow/RainbowWallet.tsx
packages/wallets/src/evm/connectors/rainbow/index.ts
packages/wallets/src/evm/wallets/rainbow-wallet.ts

Not able to connect to Rainbow Wallet on mobile. This issue got introduced with https://github.com/thirdweb-dev/js/commit/eb463735e2f784cd1d212a982835af95cf60766b. This PR fixes that

Fix Rainbow wallet connection in mobile

---

.github/contributing.md

Update contributing guide to explain release-pr flow

Update contributing guide to explain release-pr flow

---

.changeset/seven-flies-heal.md
packages/react/src/wallet/ConnectWallet/ConnectModal.tsx

Fix SmartWallet and Safe connection issue that was introduced in https://github.com/thirdweb-dev/js/commit/b29ec675f9c41c49c015af2427d5402367c06c73
* when connecting to a safe or smartWallet - we first connect to a personal wallet. The issue was that when using ConnectWallet for connecting to safe or smartWallet - it was only connecting to the personal wallet and not going to next step of connecting to the safe/smartWallet - this PR fixes that 
No changes made to public API

Fix SmartWallet and Safe connection issue

---

.changeset/wild-icons-argue.md
packages/sdk/src/evm/common/any-evm-constants.ts

Custom gasprice for bittorrent mainnet create2 factory deployment

[SDK] Custom gasprice BitTorrent mainnet

---

.changeset/thirty-lions-clean.md
packages/service-utils/package.json
packages/service-utils/src/cf-worker/index.ts
packages/service-utils/src/core/api.ts
packages/service-utils/src/core/authorize/client.test.ts
packages/service-utils/src/core/authorize/client.ts
packages/service-utils/src/core/authorize/index.ts
packages/service-utils/src/core/authorize/service.test.ts
packages/service-utils/src/core/authorize/service.ts
packages/service-utils/src/core/rateLimit/index.ts
packages/service-utils/src/core/rateLimit/rateLimit.test.ts
packages/service-utils/src/core/rateLimit/types.ts
packages/service-utils/src/core/usageLimit/index.ts
packages/service-utils/src/core/usageLimit/types.ts
packages/service-utils/src/core/usageLimit/usageLimit.test.ts
packages/service-utils/src/mocks.ts
packages/service-utils/src/node/index.ts
pnpm-lock.yaml

feat: rate limit worker

---

.changeset/wicked-cats-deliver.md
packages/cli/package.json

allow node 20 users to use our CLI :)

[cli] - unlock node 20

---

.changeset/fair-badgers-speak.md
packages/service-utils/src/cf-worker/usage.ts

Adds fields in usage tracker for platform metrics.

chore: Add platform metrics fields

---

.changeset/four-toys-smoke.md
packages/chains/chains/225.ts
packages/chains/chains/274.ts
packages/chains/src/index.ts
packages/unity-js-bridge/src/thirdweb-bridge.ts

Added EmbeddedWallet login option to Unity bridge

[Unity] Add EmbeddedWallet option WebGL

---

.changeset/clever-gifts-love.md
.changeset/neat-mugs-accept.md
.changeset/quiet-dragons-worry.md
.changeset/two-papayas-yell.md

Some packages where set as minor update but they are minor upgrades

Downgrade sdk to patch update

---

.changeset/young-emus-change.md
packages/react/src/wallet/ConnectWallet/Details.tsx
packages/react/src/wallet/ConnectWallet/NetworkSelector.tsx
packages/react/src/wallet/ConnectWallet/WalletSelector.tsx
packages/react/src/wallet/wallets/embeddedWallet/EmbeddedWalletOTPLoginUI.tsx
packages/react/src/wallet/wallets/paper/PaperOTPLoginUI.tsx

- Fix "Connected to Smart Wallet" shown even if not connected to Smart Wallet 
- Improved UI for Email OTP input screen
- Prevent accidental click on the thirdweb icon next to the title when clicking back button

[react] ConnectWallet UI Fixes / Improvements 

---

.github/workflows/sync-chains.yml
packages/chains/package.json
packages/chains/scripts/sync-db.ts

- setup workflow to automatically sync chains from db every hour

chore(chains): sync from db

---

.changeset/pink-squids-flash.md
packages/sdk/src/evm/constants/urls.ts
packages/storage/src/core/downloaders/storage-downloader.ts
packages/storage/src/core/uploaders/ipfs-uploader.ts
packages/wallets/src/evm/connectors/smart-wallet/lib/http-rpc-client.ts

We weren't detecting webGL platform for sdk headers

[Multi] Detect webGL platform

---

.changeset/lazy-pandas-sit.md
packages/react/src/wallet/ConnectWallet/WalletSelector.tsx

Update upsell link for connect wallet

---

.changeset/quick-feet-promise.md
packages/unity-js-bridge/src/thirdweb-bridge.ts

Fixes google popup window from being blocked in WebGL

[Unity] Fix Google popup blocker

---

.changeset/witty-spiders-sell.md
packages/sdk/src/evm/core/wallet/user-wallet.ts

[SDK] Update transfer function for user wallet

---

.changeset/dull-cups-invite.md
packages/sdk/src/evm/common/feature-detection/resolveContractUriFromAddress.ts

Handle old school upgradeable proxies + optimize resolve proxy implementations

[SDK] handle upgradeable proxies and optimize proxy resolution

---

.changeset/tidy-tips-flow.md
packages/contracts-js/package.json
packages/sdk/src/evm/common/any-evm-utils/computeDeploymentInfo.ts
packages/sdk/src/evm/constants/erc721-features.ts
packages/sdk/src/evm/core/classes/factory.ts
packages/sdk/src/evm/core/sdk.ts
packages/sdk/test/evm/any-evm-keyless.test.ts
packages/sdk/test/evm/before-setup.ts
packages/sdk/test/evm/marketplace-v3.test.ts
packages/sdk/test/evm/mock/directListingsMetadata.ts
packages/sdk/test/evm/mock/englishAuctionsMetadata.ts
packages/sdk/test/evm/mock/marketplaceV3Metadata.ts
packages/sdk/test/evm/mock/offersMetadata.ts
pnpm-lock.yaml

Update deployment setup and tests for MarketplaceV3 latest, which includes:
- change from plugin pattern to dynamic pattern
- constructor API change (now accepts a struct param)
Other changes:
- Update any-evm-keyless test file
- Store mock metadata for marketplace and its extensions (to not depend on ipfs)

Update deployment setup

---

.changeset/smooth-phones-remain.md
.changeset/wise-emus-cheer.md
packages/react-native/src/evm/components/ConnectWalletDetails/SmartWalletAdditionalActions.tsx
packages/react-native/src/evm/components/ConnectWalletDetails/WalletDetailsModalHeader.tsx
packages/react-native/src/evm/components/ConnectWalletFlow/ChooseWallet/ChooseWallet.tsx
packages/react-native/src/evm/components/ConnectWalletFlow/ConnectWalletButton.tsx
packages/react-native/src/evm/components/ConnectWalletFlow/ConnectWalletFlow.tsx
packages/react-native/src/evm/components/ConnectWalletFlow/ConnectingWallet/ConnectingWalletHeader.tsx
packages/react-native/src/evm/components/ConnectWalletFlow/LocalWalletImportModal.tsx
packages/react-native/src/evm/components/ConnectWalletFlow/SmartWallet/SmartWalletFlow.tsx
packages/react-native/src/evm/components/MainModal.tsx
packages/react-native/src/evm/components/PasswordInput.tsx
packages/react-native/src/evm/components/ReceiveButton.tsx
packages/react-native/src/evm/components/SendFunds/SendButton.tsx
packages/react-native/src/evm/components/SendFunds/TokenSelector.tsx
packages/react-native/src/evm/components/base/LoadingTextAnimation.tsx
packages/react-native/src/evm/components/base/NetworkButton.tsx
packages/react-native/src/evm/components/base/Toast.tsx
packages/react-native/src/evm/components/base/WalletButtonSquare.tsx
packages/react-native/src/evm/components/base/modal/ModalFooter.tsx
packages/react-native/src/evm/components/base/modal/ModalHeaderTextClose.tsx
packages/react-native/src/evm/providers/ui-context-provider.tsx
packages/react-native/src/evm/wallets/wallets/embedded/EmbeddedConnectionUI.tsx
packages/react-native/src/evm/wallets/wallets/embedded/EmbeddedSelectionUI.tsx
packages/react-native/src/evm/wallets/wallets/magic-link.tsx
packages/react-native/src/evm/wallets/wallets/wallet-connect/WalletConnectUI.tsx
packages/react-native/src/evm/wallets/wallets/wallet-connect/WalletLoadingThumbnail.tsx

[RN] Correctly use custom themes

---

.changeset/five-rats-sell.md
packages/sdk/src/evm/common/marketplace.ts
packages/sdk/src/evm/core/classes/marketplace-auction.ts
packages/sdk/src/evm/core/classes/marketplace-direct.ts
packages/sdk/src/evm/core/classes/marketplacev3-direct-listings.ts
packages/sdk/src/evm/core/classes/marketplacev3-english-auction.ts

[SDK] Perf improv to marketplace methods

---

.changeset/dirty-rockets-push.md
packages/contracts-js/package.json
pnpm-lock.yaml

[ContractsJS] update contracts-js package

---

.changeset/poor-pans-agree.md
packages/sdk/src/evm/core/classes/contract-published-metadata.ts
packages/sdk/src/evm/core/classes/contract-publisher.ts

Exposing some of our utility functions

[SDK] expose utility functions for abi / sources

---

packages/sdk/test/evm/any-evm-keyless.test.ts

[SDK] fix marketplace tests

---

packages/react-native/README.md

[RN] Update README

---

.changeset/modern-panthers-grow.md
packages/wallets/src/evm/connectors/smart-wallet/utils.ts

[Wallet] Fix getSmartWalletAddress util function

---

.changeset/silver-dodos-grow.md
packages/wallets/src/evm/wallets/smart-wallet.ts

[wallets] - Fix chains package not tree-shaken because of SmartWallet 

---

.changeset/fresh-toys-remember.md
packages/react/src/wallet/ConnectWallet/ConnectWallet.tsx

[React] Fix sign in button display logic

---

.changeset/great-cows-sleep.md
packages/react/src/evm/components/Web3Button/index.tsx
packages/react/src/wallet/ConnectWallet/ConnectWallet.tsx
packages/react/src/wallet/ConnectWallet/Details.tsx
packages/react/src/wallet/ConnectWallet/Modal/ConnectModalInline.tsx

[React] Add option to hide personal wallet switch to React

---

.changeset/hip-bananas-watch.md
packages/service-utils/src/cf-worker/usage.ts

Adds "checkout" as a valid usage type.

chore: Add checkout as a usage type

---

.changeset/empty-kangaroos-speak.md
packages/chains/chains/122.ts
packages/chains/chains/13337.ts
packages/chains/chains/1666600002.ts
packages/chains/chains/1666600003.ts
packages/chains/chains/1748.ts
packages/chains/chains/195.ts
packages/chains/chains/196.ts
packages/chains/chains/206.ts
packages/chains/chains/207.ts
packages/chains/chains/2222.ts
packages/chains/chains/248.ts
packages/chains/chains/29548.ts
packages/chains/chains/333333.ts
packages/chains/chains/3636.ts
packages/chains/chains/3637.ts
packages/chains/chains/399.ts
packages/chains/chains/4337.ts
packages/chains/chains/5003.ts
packages/chains/chains/52014.ts
packages/chains/chains/5201420.ts
packages/chains/chains/570.ts
packages/chains/chains/68840142.ts
packages/chains/chains/894538.ts
packages/chains/chains/9322252.ts
packages/chains/chains/9322253.ts
packages/chains/chains/988207.ts
packages/chains/src/index.ts

[Chore(chains)] sync chains

---

.changeset/swift-brooms-pump.md
packages/react-native/package.json
pnpm-lock.yaml

[RN] Updated safe-area-context package to 4.7.4

---

.changeset/tricky-turkeys-mate.md
packages/react-core/src/core/providers/thirdweb-wallet-provider.tsx
packages/wallets/src/evm/connectors/embedded-wallet/index.ts
packages/wallets/src/evm/connectors/smart-wallet/index.ts
packages/wallets/src/evm/connectors/smart-wallet/lib/base-api.ts
packages/wallets/src/evm/connectors/smart-wallet/lib/erc4337-provider.ts
packages/wallets/src/evm/connectors/smart-wallet/lib/provider-utils.ts
packages/wallets/src/evm/wallets/embedded-wallet.ts

- Dont remove local storage data on autoconnection errors
- Improve smart wallet connection performance

[SmartWallet, React] Smart wallet performance and auto connect fixes

---

.changeset/twenty-stingrays-crash.md
packages/wallets/src/evm/connectors/embedded-wallet/index.ts

[EmbeddedWallet] fix switch chains logic

---

.changeset/gentle-kings-shout.md
packages/unity-js-bridge/src/thirdweb-bridge.ts

- Added Unity WebGL Support for session keys, adding and removing smart wallet signers
- Updated interface
- Set Smart Wallet Options, Build [this branch](https://github.com/thirdweb-dev/unity-sdk/pull/128) to WebGL
- sdk.wallet.AddAdmin/RemoveAdmin/CreateSessionKey should work
NB: request validity options are not used as they are not exposed in TS

[Unity] Support Add/Remove Admin and Create Session Key for SW

---

.changeset/six-experts-behave.md
packages/react-native/src/evm/wallets/connectors/embedded-wallet/embedded/auth.ts
packages/react-native/src/evm/wallets/connectors/embedded-wallet/embedded/helpers/api/fetchers.ts
packages/react-native/src/evm/wallets/connectors/embedded-wallet/embedded/helpers/constants.ts
packages/react-native/src/evm/wallets/connectors/embedded-wallet/embedded/helpers/errors.ts
packages/react-native/src/evm/wallets/connectors/embedded-wallet/embedded/helpers/wallet/creation.ts

[RN] Improves error messages for embedded wallet

---

.changeset/olive-mayflies-wash.md
packages/react-native/src/evm/components/Web3Button.tsx
packages/react/src/evm/components/Web3Button/index.tsx

As discussed with Joaquim, we no longer use this so it's going to be removed from both code and docs

[React, React native] Remove `overrides` prop from Web3Button

---

.changeset/sixty-hornets-act.md
packages/wallets/src/evm/connectors/smart-wallet/lib/userop-event.ts

[Wallets] Look at last 10 blocks for recently submitted userOp

---

.changeset/sweet-news-kick.md
packages/unity-js-bridge/src/thirdweb-bridge.ts

Related Unity PR https://github.com/thirdweb-dev/unity-sdk/pull/131

[Unity] Add new tx/block processing methods to match static C# counterparts

---

.changeset/serious-pugs-return.md
packages/react-core/src/core/providers/thirdweb-wallet-provider.tsx
packages/react/src/wallet/ConnectWallet/Details.tsx
packages/react/src/wallet/wallets/magic/magicLink.tsx

* Fixes https://github.com/thirdweb-dev/js/issues/1708 
* Fixes smart wallet icon shown even after clicking on "Switch to Personal wallet" in ConnectWallet dropdown
* Connect MagicLink directly to the `activeChain` instead of `Ethereum`

[react] Fix SmartWallet + MagicLink social login connection, Fix WalletIcon in CW

---

.changeset/forty-ducks-talk.md
packages/react-core/src/core/providers/thirdweb-wallet-provider.tsx

[React] Do not set disconnected if connecting

---

.changeset/forty-vans-switch.md
packages/sdk/src/evm/core/classes/contract-wrapper.ts

[SDK] Fix undefined error for unknow chains

---

packages/sdk/src/evm/constants/addresses/getDefaultTrustedForwarders.ts
packages/sdk/src/evm/core/classes/contract-wrapper.ts
packages/sdk/src/evm/core/classes/transactions.ts
packages/sdk/src/evm/zksync/constants/addresses.ts

[SDK] Handle other possible undefined cases for unknown chains

---

.changeset/long-eels-shout.md
packages/sdk/src/evm/core/sdk.ts

[SDK] Enable deployments for older AccountFactory contracts

---

.changeset/orange-bobcats-brush.md
packages/sdk/src/evm/common/metadata-resolver.ts
packages/sdk/src/evm/core/classes/transactions.ts

[SDK] dont fetch metadata from CDN for local nodes

---

.changeset/brave-actors-refuse.md
packages/react-core/src/evm/hooks/wallet.ts
packages/react-core/src/evm/index.ts

[react-core] Add hook: useBalanceForAddress

---

.changeset/cuddly-kings-melt.md
packages/sdk/src/evm/common/fetchContractMetadata.ts

[SDK] propagate isPartialABI

---

.changeset/giant-jars-visit.md
packages/react-core/src/core/providers/thirdweb-wallet-provider.tsx
packages/react-core/src/core/utils/receiver.ts
packages/react-core/src/evm/index.ts
packages/react-native/src/evm/components/ConnectWalletDetails/ConnectAppField.tsx
packages/react-native/src/evm/components/ConnectWalletDetails/SessionProposalModal.tsx
packages/react-native/src/evm/components/ConnectWalletDetails/SessionRequestModal.tsx
packages/react-native/src/evm/providers/context-provider.tsx
packages/react-native/src/evm/wallets/hooks/useWalletConnectListener.ts

[ReactCore] Share WalletConnecthandler in react core

---

.changeset/proud-bees-report.md
packages/chains/src/index.ts

[storage] Add Base Sepolia to `defaultChains`

---

.changeset/early-schools-act.md
packages/react-native/src/core/storage/uploader.ts
packages/react-native/src/evm/components/base/ImageSvgUri.tsx
packages/react-native/src/evm/constants/headers.ts
packages/react-native/src/evm/utils/version.ts
packages/react-native/src/evm/wallets/connectors/embedded-wallet/embedded/auth.ts
packages/react-native/src/evm/wallets/connectors/embedded-wallet/embedded/helpers/api/fetchers.ts
packages/react-native/src/evm/wallets/connectors/embedded-wallet/embedded/helpers/constants.ts
packages/react-native/src/index.ts

[RN] Adds version header to ews calls

---

.changeset/friendly-boats-wonder.md
packages/react-core/src/core/providers/thirdweb-wallet-provider.tsx

when user clicks on "Switch to personal wallet" when they are connected to smart wallet and reloads the page, auto-connect to smart wallet. context - https://thirdwebdev.slack.com/archives/C04PAQYN5HB/p1701168918336259

improved smart wallet autoconnect 

---

.changeset/tricky-keys-crash.md
packages/react/src/wallet/ConnectWallet/Modal/ConnectModal.tsx
packages/react/src/wallet/wallets/walletConnect/WalletConnectScan.tsx
packages/react/src/wallet/wallets/walletConnect/walletConnect.tsx
packages/wallets/src/evm/connectors/wallet-connect/index.ts
packages/wallets/src/evm/wallets/wallet-connect.ts

[react] Add "Open Official WalletConnect Modal" in ConnectWallet  

---

.changeset/odd-mayflies-happen.md
packages/sdk/src/evm/common/gas-price.ts
packages/sdk/src/evm/core/sdk.ts

[SDK] expose BaseFee in `getDynamicFeeData()` 

---

.changeset/shaggy-eggs-design.md
packages/react/package.json
packages/react/src/components/Modal.tsx
packages/react/src/wallet/wallets/headlessConnectUI.tsx
packages/react/src/wallet/wallets/walletConnect/walletConnect.tsx
pnpm-lock.yaml

context - https://thirdwebdev.slack.com/archives/C059AQG131Q/p1702018335355899?thread_ts=1701960973.828869&cid=C059AQG131Q

[react] - Add option to only show Official WC Modal, Fix focus trap when CW Modal is hidden

---

packages/sdk/src/evm/contracts/smart-contract.ts
packages/sdk/src/evm/core/classes/account-factory.ts
packages/sdk/src/evm/core/classes/account.ts
packages/sdk/src/evm/index.ts
packages/wallets/src/evm/connectors/smart-wallet/lib/base-api.ts

[SDK] cleanup

---

packages/sdk/src/evm/index.ts
packages/wallets/src/evm/connectors/smart-wallet/utils.ts

[SDK] Export contract verifier

---

.changeset/polite-candles-rule.md
packages/react-core/src/core/providers/thirdweb-provider.tsx
packages/react-core/src/evm/contexts/thirdweb-auth.tsx
packages/react-core/src/evm/hooks/auth/useLogin.ts
packages/react-core/src/evm/hooks/auth/useLogout.ts
packages/react-core/src/evm/hooks/auth/useUser.ts
packages/react-core/src/evm/hooks/storage/useStorage.ts
packages/react-native/src/evm/providers/thirdweb-provider.tsx
packages/react-native/src/evm/styles/ThemeProvider.tsx
packages/react-native/src/evm/wallets/wallets/coinbase-wallet.ts
packages/react-native/src/evm/wallets/wallets/local-wallet.tsx
packages/react-native/src/evm/wallets/wallets/metamask-wallet.ts
packages/react-native/src/evm/wallets/wallets/rainbow-wallet.ts
packages/react-native/src/evm/wallets/wallets/smart-wallet.tsx
packages/react-native/src/evm/wallets/wallets/trust-wallet.ts
packages/react-native/src/evm/wallets/wallets/wallet-connect/wallet-connect.tsx

[RN/React-Core] Improve comments

---

.changeset/pink-bobcats-kneel.md
packages/react-native/package.json
pnpm-lock.yaml

[RN] Support expo versions >=47 <50

---

.changeset/hot-foxes-pay.md
packages/sdk/src/evm/common/plugin/getCompositePluginABI.ts
packages/sdk/src/evm/common/plugin/joinABIs.ts
packages/sdk/src/evm/common/verification.ts

Fetch and use transaction hash to get deployment data for a contract.

[SDK] Fix verification

---

.changeset/sixty-students-peel.md
packages/service-utils/src/core/services.ts

chore: added payments to scope

---

packages/merkletree/tsconfig.json
packages/wallets/hardhat.config.ts
packages/wallets/package.json
packages/wallets/src/evm/connectors/smart-wallet/lib/base-api.ts
packages/wallets/src/evm/connectors/smart-wallet/lib/http-rpc-client.ts
packages/wallets/test/smart-wallet-integration.test.ts
packages/wallets/test/smart.disabled-test.ts
packages/wallets/tsconfig.json
pnpm-lock.yaml

Added a integration test (hits mumbai prod) to catch any issues easier

[Wallets] simple integration test for smart wallets

---

.changeset/brown-elephants-type.md

payments package needs to be update to 1.0.1 to export latest interfaces

add patch bump to payments package

---

.changeset/angry-elephants-pretend.md
packages/react-native/src/evm/components/ConnectWallet.tsx
packages/react-native/src/evm/components/ConnectWalletDetails/ConnectWalletDetailsModal.tsx
packages/react-native/src/evm/components/ConnectWalletDetails/WalletDetailsButton.tsx

[RN] Fixes custom balance token display in ConnectWallet details button

---

.changeset/forty-needles-compare.md
packages/payments/src/lib/CreatePaymentElement.ts

- Payments minor bug fix importing package.json

Payments: Minor bug fix package.json import

---

.changeset/hungry-ways-protect.md
packages/react-native/src/evm/components/ConnectWallet.tsx
packages/react-native/src/evm/components/ConnectWalletDetails/ConnectWalletDetailsModal.tsx
packages/react-native/src/evm/components/ConnectWalletDetails/WalletDetailsButton.tsx
packages/react-native/src/evm/components/ConnectWalletDetails/WalletDetailsModalHeader.tsx

```ts
<ConnectWallet hideDisconnect={true} />
```

[RN] Adds hideDisconnect prop to ConnectWallet comp

---

.changeset/ten-jokes-tickle.md
packages/react-core/src/evm/hooks/async/drop.ts

Fixes https://github.com/thirdweb-dev/js/issues/2110

Fix useUnclaimedNFTs hook return type

---

packages/sdk/test/evm/any-evm-keyless.test.ts

fix(test): fix condition to run deploy marketplacev3

---

.changeset/rude-candles-stare.md
packages/react-native/src/evm/providers/thirdweb-provider.tsx

[RN] Correctly pass sdkOptions down

---

.github/workflows/snippets.yml
.github/workflows/typedoc.yml
.gitignore
package.json
packages/react-core/package.json
packages/react-core/scripts/typedoc.mjs
packages/react-native/scripts/typedoc.mjs
packages/react/package.json
packages/react/scripts/typedoc.mjs
packages/sdk/package.json
packages/sdk/scripts/typedoc.mjs
packages/storage/package.json
packages/storage/scripts/typedoc.mjs
packages/typedoc-gen/src/index.ts
packages/wallets/scripts/typedoc.mjs
scripts/generate-snippets/index.mjs
scripts/generate-snippets/utils/create-csharp-snippet.mjs
scripts/generate-snippets/utils/create-react-snippet-from-mapping.mjs
snippets/readme.md
turbo.json

* Add typedoc workflow for generating the full references - for new docs website
* Add Snippets workflow for generating the snippets.json files - for dashboard
`scripts/generate-snippets/*` files are taken from the old docs repo and modified slightly to replace the git submodules usage

Add typedoc and snippets workflows 

---

.changeset/blue-coins-attend.md
packages/wallets/src/evm/connectors/local-wallet/wrapped-signer.ts

[RN] Implement signedData for LocalWallet

---

.github/workflows/release.yml

build before snippet generation

---

.changeset/hot-ears-laugh.md
packages/react-native/package.json
pnpm-lock.yaml

[RN] Upgrade min RN version requirenment to 0.71 and mmkv to 2.11.0

---

.changeset/serious-ears-beam.md
packages/react/src/evm/index.ts
packages/react/src/evm/providers/wallet-ui-states-provider.tsx
packages/react/src/wallet/ConnectWallet/ConnectWallet.tsx

Solves https://github.com/thirdweb-dev/js/issues/2178 requirement

[react] add useSetWalletModalConfig hook

---

packages/sdk/src/evm/index.ts

export sig minting classes for docs

---

.changeset/itchy-hairs-lie.md
packages/react/src/evm/locales/en.ts
packages/react/src/evm/locales/es.ts
packages/react/src/evm/locales/ja.ts
packages/react/src/evm/locales/tl.ts
packages/react/src/evm/locales/types.ts
packages/react/src/wallet/wallets/embeddedWallet/EmbeddedWalletFormUI.tsx
packages/react/src/wallet/wallets/embeddedWallet/EmbeddedWalletOTPLoginUI.tsx
packages/react/src/wallet/wallets/embeddedWallet/EmbeddedWalletSocialLogin.tsx

show explicit error when max wallets amount exceeded

[React] show embedded wallet free tier error msg in connect

---

.github/workflows/sync-chains.yml

fix sync chains workflow

---

.github/workflows/sync-chains.yml

sync-chains add step to create changeset

---

.changeset/yellow-numbers-tickle.md
packages/react/src/wallet/ConnectWallet/ConnectWallet.tsx
packages/react/src/wallet/ConnectWallet/Details.tsx

allows doing - https://github.com/thirdweb-dev/js/pull/2216

[react] add detailsModalFooter prop in ConnectWallet

---

.changeset/red-terms-talk.md
packages/unity-js-bridge/src/thirdweb-bridge.ts

Unity v4.6.1

---

.changeset/four-weeks-agree.md
packages/service-utils/src/node/index.ts

[ServiceUtil] add latency prop to logHttpRequest

---

.changeset/wet-llamas-divide.md
packages/unity-js-bridge/src/thirdweb-bridge.ts

Unity 4.6.2

---

.changeset/bright-boxes-crash.md
packages/sdk/src/evm/common/snapshots.ts

[SDK] Export MerkleTree helper functions

---

.changeset/light-pumas-collect.md
packages/sdk/src/evm/core/classes/internal/contract-wrapper.ts
packages/sdk/src/evm/core/classes/transactions.ts
packages/sdk/src/evm/schema/sdk-options.ts

Add sdk support for engine relayer forwarderAddress, chainless domain forwarder

add sdk support for engine relayer options

---

.changeset/healthy-garlics-greet.md
packages/sdk/src/evm/lib/static-batch-rpc.ts

[SDK] Lower max RPC batch size

---

.changeset/mighty-crabs-greet.md
packages/unity-js-bridge/src/thirdweb-bridge.ts

[Unity] Support Wallet.GetSignerAddress

---

.changeset/forty-nails-perform.md
packages/sdk/src/evm/constants/urls.ts
packages/sdk/src/evm/lib/static-batch-rpc.ts
packages/sdk/src/evm/schema/sdk-options.ts

[SDK] expose rpcBatchingOptions

---

.changeset/red-trees-yell.md
packages/unity-js-bridge/src/thirdweb-bridge.ts

Unity 4.6.4

---

packages/storage/test/ipfs.test.ts

fix storage test

---

packages/sdk/src/evm/common/any-evm-utils/deployCreate2Factory.ts
packages/sdk/src/evm/common/any-evm-utils/deployDirectDeterministic.ts
packages/sdk/src/evm/common/any-evm-utils/getKeylessTxn.ts
packages/sdk/src/evm/common/any-evm-utils/getThirdwebContractAddress.ts
packages/sdk/src/evm/common/any-evm-utils/isContractDeployed.ts
packages/sdk/src/evm/common/any-evm-utils/predictThirdwebContractAddress.ts
packages/sdk/src/evm/common/deploy.ts
packages/sdk/src/evm/common/feature-detection/extractFeatures.ts
packages/sdk/src/evm/common/feature-detection/toJSType.ts
packages/sdk/src/evm/contracts/smart-contract.ts
packages/sdk/src/evm/core/classes/contract-encoder.ts
packages/sdk/src/evm/core/classes/contract-events.ts
packages/sdk/src/evm/core/classes/contract-metadata.ts
packages/sdk/src/evm/core/classes/drop-claim-conditions.ts
packages/sdk/src/evm/core/classes/drop-erc1155-claim-conditions.ts
packages/sdk/src/evm/core/classes/erc-1155-signature-mintable.ts
packages/sdk/src/evm/core/classes/erc-1155.ts
packages/sdk/src/evm/core/classes/erc-20-signature-mintable.ts
packages/sdk/src/evm/core/classes/erc-20.ts
packages/sdk/src/evm/core/classes/erc-721-with-quantity-signature-mintable.ts
packages/sdk/src/evm/core/classes/erc-721.ts
packages/sdk/src/evm/core/classes/transactions.ts
packages/sdk/src/evm/core/sdk.ts
packages/sdk/tsdoc.json

Doc Grouping

---

.changeset/four-adults-confess.md
packages/sdk/src/evm/core/classes/erc-1155.ts
packages/sdk/src/evm/core/classes/internal/erc1155/erc-1155-lazy-mintable.ts
packages/sdk/test/evm/edition-drop-v4.test.ts
pnpm-lock.yaml

[SDK] updateMetadata for edition drop contracts

---

.changeset/unlucky-cows-explode.md
packages/unity-js-bridge/src/thirdweb-bridge.ts

Unity 4.7.1

---

.changeset/shy-nails-help.md
packages/sdk/src/evm/common/feature-detection/extractMinimalProxyImplementationAddress.ts
packages/sdk/test/evm/address.test.ts
packages/sdk/test/evm/feature-detection.test.ts

EIP7511 minimal proxy with PUSH0 opcode (https://eips.ethereum.org/EIPS/eip-7511)

[SDK] Resolve EIP7511 minimal proxy

---

.changeset/violet-cameras-listen.md
packages/service-utils/src/core/services.ts

Add thirdweb Pay to Services definition list. Note: Update js sdk version on api-server before dashboard.
```Address: ``` 0x55C2c599bE2ce16c58579A779625547DDBfD94f1

Add pay to Services list

---

.changeset/serious-phones-itch.md
legacy_packages/react/src/wallet/ConnectWallet/Details.tsx
legacy_packages/react/src/wallet/wallets/embeddedWallet/ExportPrivateKey.tsx

Introduce the ability to export private keys from the embedded wallet.
1. **UI Changes**:
- Added a button for exporting private keys in the `ConnectedWalletDetails` component.
- Integrated `ExportPrivateKey` component to handle the UI for key export.
2. **New Component**:
- Created `ExportPrivateKey` to facilitate the export functionality using an `<iframe>`.
1. Navigate to the wallet connection interface.
2. Connect using an embedded wallet.
3. Click on the

feat: add export private key functionality

---

.github/labeler.yml
.github/workflows/label.yml

This PR introduces a new labeler configuration and workflow to automate the labeling of pull requests based on modified file paths.
- Added a `.github/labeler.yml` file to define the labeling rules.
- Added a `.github/workflows/label.yml` workflow to apply the labels using the defined rules.
1. Create a pull request that modifies files in one of the defined paths (e.g., `apps/dashboard/**/*`).
2. Verify that the pull request gets labeled correctly based on the path.
Automating the labeling process helps in triaging pull requests, making it easier to manage and prioritize them.
---

[Chore] Add labeler workflow configuration

---

apps/dashboard/src/@3rdweb-sdk/react/hooks/useApi.ts
apps/dashboard/src/app/login/auth-actions.ts
apps/dashboard/src/components/onboarding/index.tsx

[Refactor] Remove unused `useConfirmEmbeddedWallet` hook and clean up onboarding flow

---

apps/dashboard/src/components/engine/engine-instances-table.tsx

The condition was correct, but the action was not

Updates: Engine

---

packages/thirdweb/src/transaction/actions/wait-for-tx-receipt.test.ts
packages/thirdweb/src/wallets/eip5792/wait-for-bundle.test.ts

fix(docs): tsdoc linting

---

.changeset/honest-adults-divide.md
.github/pull_request_template.md
packages/thirdweb/src/adapters/ethers5.ts

Fixed wrong determined direct deploy addreses due to missing nonce in the adapter ethers tx result

fix(ethers5adapter): correct transaction result nonces handling

---

.changeset/eighty-poets-doubt.md
packages/thirdweb/src/react/core/hooks/transaction/useSendTransaction.ts

Add testMode in buyWithCrypto in useSendTransaction

Crypto test mode use send transaction

---

apps/dashboard/src/app/(dashboard)/(chain)/[chain_id]/[contractAddress]/_utils/getContractFromParams.ts

Added authentication token support for contract retrieval in the dashboard.
- Imported `getAuthToken` function from a new location.
- Updated the `getContractPageParamsInfo` function to attempt to get an auth token.
- Modified the `getContract` call to include the auth token in the client if available.
- Adjusted import statements for better organization and readability.
1. Navigate to the dashboard and access a contract page.
2. Verify that the contract information is correctly retrieved with authentication.
3. Test both authenticated and unauthenticated scenarios to ensure proper functionality.
This change enhances security and allows for authenticated access to contract information. By incorporating the auth token into the client, we can ensure that users have the appropriate …

fix auth token

---

apps/dashboard/src/components/contract-functions/interactive-abi-function.tsx

[Dashboard] fix: Use formatted ABI for contract function calls

---

apps/portal/src/app/react/v5/connecting-wallets/hooks/page.mdx

[Portal] fix: Update useAutoConnect hook reference link

---

.changeset/nervous-frogs-pay.md
apps/playground-web/src/components/sign-in/hooks.tsx
packages/thirdweb/src/wallets/wallet-connect/controller.ts

[SDK] fix: Improve WalletConnect mobile connection handling

---

apps/dashboard/src/app/login/onboarding/ChoosePlan.tsx

update plan selection copy and tracking

---

.changeset/evil-cases-read.md
packages/react-native-adapter/package.json
packages/thirdweb/package.json
packages/thirdweb/src/wallets/coinbase/coinbase-mobile.ts
pnpm-lock.yaml

[SDK] Update @mobile-wallet-protocol/client to 1.0.0
